// Explicit Shopify adapters; these fixtures do not certify platform/browser behavior.
const fs=require('node:fs'),{Liquid}=require('liquidjs'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(p,'utf8'),engine=new Liquid({root:'snippets',extname:'.liquid'});
const escape=x=>String(x??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
for(const [name,fn]of Object.entries({json:x=>JSON.stringify(x??null),money:x=>'$'+(Number(x||0)/100).toFixed(2),money_with_currency:x=>'$'+(Number(x||0)/100).toFixed(2)+' USD',asset_url:x=>'/assets/'+x,shopify_asset_url:x=>'/shopify/'+x,stylesheet_tag:x=>`<link href="${x}" rel="stylesheet">`,image_url:(x,args)=>(x?.preview_image?.url||x?.url||x?.src||'/media.jpg')+'?width='+(args?.[1]||800),image_tag:(x,...args)=>'<img src="'+escape(x)+'" width="800" height="600" alt="">',structured_data:()=>'{"@type":"Product"}',media_tag:x=>x.media_type==='video'?'<video controls></video>':x.media_type==='external_video'?'<iframe title="Video" src="https://www.youtube.com/embed/test"></iframe>':'<model-viewer></model-viewer>',metafield_tag:x=>'<span>'+escape(x?.value||'')+'</span>',color_contrast:()=>21,t:x=>x,payment_button:()=>'<button type="button" class="shopify-payment-button">Buy now</button>',placeholder_svg_tag:()=>'<svg></svg>'}))engine.registerFilter(name,fn);
const defaults=f=>Object.fromEntries((f||[]).filter(x=>x.id).map(x=>[x.id,x.default??null]));
const globalSettings=Object.assign({},...JSON.parse(read('config/settings_schema.json')).map(g=>defaults(g.settings)));
const unpack=name=>{const parts=read('sections/'+name+'.liquid').split('{% schema %}');return{liquid:parts[0],schema:JSON.parse(parts[1].split('{% endschema %}')[0])}};
function platform(text){return text.replace(/{%-?\s*stylesheet\s*-?%}/g,'<style>').replace(/{%-?\s*endstylesheet\s*-?%}/g,'</style>').replace(/\n[ \t]+comment\n[\s\S]*?\n[ \t]+endcomment\n/g,'\n').replace(/{%-?\s*form\s+[^%]+%}/g,tag=>{const id=tag.match(/\bid:\s*([\w.]+)/),klass=tag.match(/\bclass:\s*'([^']+)'/);return '<form method="post" action="/fr/cart/add"'+(id?' id="{{ '+id[1]+' }}"':'')+(klass?' class="'+klass[1]+'"':'')+(tag.includes('data-cart-drawer-add')?' data-cart-drawer-add':'')+'>';}).replace(/{%-?\s*endform\s*-?%}/g,'</form>').replace(/{%-?\s*render\s+block\s*-?%}/g,'<div data-platform-app>App adapter</div>').replace(/{%-?\s*(paginate|endpaginate)\b[^%]*%}/g,'');}
const photo=(n=1)=>({id:n,url:'https://cdn.example.test/image-'+n+'.jpg',width:800,height:600,aspect_ratio:4/3,alt:'Photo <safe>'});
const media=[{id:1,media_type:'image',preview_image:photo(1)},{id:2,media_type:'video',preview_image:photo(2)},{id:3,media_type:'image',preview_image:photo(3)}];
const variants=[{id:10,options:['Small','Red'],option1:'Small',option2:'Red',title:'Small / Red',price:1000,compare_at_price:1250,available:true,sku:'',featured_media:media[0],featured_image:photo(1),selling_plan_allocations:[{selling_plan:{id:45},price:800,compare_at_price:1000}]},{id:100,options:['Large','Blue'],option1:'Large',option2:'Blue',title:'Large / Blue',price:2000,compare_at_price:2000,available:true,sku:'SKU100',featured_media:media[2],featured_image:photo(3),quantity_rule:{min:2,max:6,increment:2},selling_plan_allocations:[{selling_plan:{id:90},price:1500,compare_at_price:2000}]},{id:101,options:['Small','Blue'],option1:'Small',option2:'Blue',title:'Small / Blue',price:2000,compare_at_price:2500,available:false,sku:'OUT',selling_plan_allocations:[]}].map(v=>({...v,url:'/fr/products/test?variant='+v.id,metafields:{custom:{swatch:{type:'color',value:'#006699'}}}}));
const product={id:1,handle:'test',url:'/fr/products/test',title:'Product <safe>',vendor:'Vendor <safe>',description:'<p>Merchant <strong>description</strong></p>',available:true,variants,selected_or_first_available_variant:variants[0],options:['Size','Color'],options_with_values:[{name:'Size',position:1,selected_value:'Small',values:['Small','Large']},{name:'Color',position:2,selected_value:'Red',values:['Red','Blue']}],media,featured_media:media[0],featured_image:photo(1),images:media.filter(m=>m.media_type==='image').map(m=>m.preview_image),selling_plan_groups:[{name:'Subscribe',selling_plans:[{id:45,name:'Monthly'},{id:90,name:'Bi-monthly'}]}],metafields:{reviews:{rating:{value:{rating:4,scale_max:5}},rating_count:{value:12}}}};
async function render(name,opts={}){const{schema,liquid}=unpack(name),id=opts.id||'one';const entries=opts.blocks??schema.presets?.[0]?.blocks??[];const blocks=entries.map((b,i)=>({id:id+'-block-'+i,type:b.type,settings:{...defaults(schema.blocks?.find(x=>x.type===b.type)?.settings),...b.settings},shopify_attributes:'data-editor-block="'+i+'"'}));return engine.parseAndRender(platform(liquid),{section:{id,settings:{...defaults(schema.settings),...opts.settings},blocks},form:{},...opts.data},{globals:{settings:globalSettings,product,routes:{root_url:'/fr/',cart_url:'/fr/cart',cart_add_url:'/fr/cart/add',cart_change_url:'/fr/cart/change',all_products_collection_url:'/fr/collections/all',product_recommendations_url:'/fr/recommendations/products'},request:{page_type:'product',design_mode:false},cart:{currency:{iso_code:'USD'}},...opts.data}});}
function dom(html,url='https://shop.test/fr/products/test'){const d=new JSDOM(html,{url,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLMediaElement.prototype.pause=function(){this.dataset.paused='true'};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});return d;}
function boot(w,files){for(const file of files){w.eval(read('assets/'+file));w.eval(read('assets/'+file));}w.document.dispatchEvent(new w.Event('DOMContentLoaded'));}
const drain=async()=>{for(let i=0;i<15;i++)await Promise.resolve()};
module.exports={read,engine,unpack,defaults,render,dom,boot,drain,product,variants,media,photo,platform};
