const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');let cases=0;
const names=['addresses','dashboard','orders','order','order-tracking'];
const routes={account_url:'/fr/account',account_login_url:'/fr/account/login',account_addresses_url:'/fr/account/addresses',account_logout_url:'/fr/account/logout',all_products_collection_url:'/fr/collections/all'};
const address={id:7,first_name:'First <safe>',last_name:'Last',company:'Company',address1:'One street',city:'Town',country:'Canada',province:'Ontario',phone:'123'};
const orders=[['paid','unfulfilled'],['unpaid','fulfilled'],['paid','partial']].map(([financial_status,fulfillment_status],i)=>({id:i+1,name:'#10'+i,created_at:'2026-09-'+(20-i),financial_status,financial_status_label:'Localized '+financial_status,fulfillment_status,fulfillment_status_label:'Localized '+fulfillment_status,total_price:1000*(i+1),item_count:1,customer_url:'/fr/account/orders/'+i,order_status_url:'/order-status/'+i,line_items:[{title:'Title <safe>',variant_title:'Size',sku:'SKU <safe>',properties:{private:'<value>',_hidden:'secret'},quantity:2,final_price:500,final_line_price:1000,fulfillment:{tracking_company:'Carrier <safe>',tracking_number:'ABC',tracking_url:'https://carrier.test/t?x=1&y=2'}}],subtotal_price:1000,total_discounts:200,shipping_price:100,tax_price:10}));
const customer={name:'Name <safe>',first_name:'Name <safe>',email:'person@example.test',orders_count:orders.length,orders,addresses:[address],default_address:address,new_address:{}};
const countryTags='<option value="Canada" data-provinces="[[&quot;ON&quot;,&quot;Ontario&quot;],[&quot;QC&quot;,&quot;Quebec&quot;]]">Canada</option><option value="France" data-provinces="[]">France</option><option value="Unknown">Unknown</option>';
f.engine.registerFilter('format_address',x=>'<p>'+String(x.address1||'').replace(/</g,'&lt;')+'</p>');
f.engine.registerFilter('default_pagination',()=>'<a href="?page=2">Next</a>');
async function host(name,opts={}){
 const{liquid,schema}=f.unpack('account-main-account-'+name),id=opts.id||'one';
 // Explicit platform form and pagination adapters; native processing is queued.
 const source=liquid.replace(/{%\s*(?:end)?paginate\b[^%]*%}/g,'').replace(/{%\s*form\s+([^%]+)%}/g,(_,args)=>{const type=args.match(/'([^']+)'/)[1],fid=args.match(/\bid:\s*([\w.]+)/),klass=args.match(/class:\s*'([^']+)'/);return '<form data-native-form="'+type+'" method="post" '+(fid?'id="{{ '+fid[1]+' }}" ':'')+(klass?'class="'+klass[1]+'"':'')+'><input type="hidden" name="form_type" value="'+type+'">';}).replace(/{%\s*endform\s*%}/g,'</form>');
 return f.engine.parseAndRender(source,{section:{id,settings:{...f.defaults(schema.settings),...opts.settings},blocks:[]}},{globals:{routes,customer,order:orders[0],form:address,all_country_option_tags:countryTags,settings:{text_base:'#111111'},request:{path:'/fr/pages/tracking',design_mode:false},paginate:{pages:2},...opts.globals}});
}
async function check(name,opts,fn){const h=await host(name,opts),d=f.dom(h);try{assert.doesNotMatch(h,/Liquid error|NaN|undefined/);fn(d.window.document,d.window,h);cases++;}finally{d.window.close()}}
(async()=>{
 for(const name of names){
  await check(name,{},(doc,w,h)=>{assert.equal(doc.querySelector('main'),null);assert(![...doc.querySelectorAll('a')].some(a=>a.getAttribute('href')==='/pages/order-tracking'));assert.equal(doc.querySelector('[onerror]'),null);for(const label of doc.querySelectorAll('label[for]'))assert(doc.getElementById(label.htmlFor),label.htmlFor);assert.equal(new Set([...doc.querySelectorAll('[id]')].map(x=>x.id)).size,doc.querySelectorAll('[id]').length);});
  await check(name,{globals:{customer:null,order:null},settings:{heading:'<img onerror=bad()>'}},doc=>assert.equal(doc.querySelector('[onerror]'),null));
  for(const st of f.unpack('account-main-account-'+name).schema.settings)for(const value of st.options?.map(x=>x.value)||(st.type==='checkbox'?[true,false]:st.type==='range'?[st.min,st.max]:[]))await check(name,{settings:{[st.id]:value}},doc=>assert(doc.querySelector('section')));
 }
 await check('dashboard',{settings:{recent_orders_limit:1,layout_style:'sidebar',show_nav_cards:false}},doc=>{assert.equal(doc.querySelectorAll('tbody tr').length,1);assert.match(doc.querySelector('.account-main-account-dashboard__layout').getAttribute('style'),/minmax/)});
 await check('orders',{settings:{dashboard_label:'Home <safe>',orders_label:'History',tracking_url:'/fr/pages/track?x=1&y=2'}},doc=>{assert.match(doc.querySelector('nav').textContent,/Home <safe>/);assert.equal(doc.querySelector('[aria-current]').textContent.trim(),'History');assert.equal(doc.querySelector('[data-qtm-account-orders-item]').dataset.orderStatus,'paid unfulfilled');});
 await check('order',{settings:{tracking_page_url:'https://provider.test/start?store=1#here'}},doc=>{assert(doc.querySelector('a[href="https://provider.test/start?store=1#here"]'));assert(doc.querySelector('a[href="https://carrier.test/t?x=1&y=2"]'));assert(!doc.body.textContent.includes('secret'));assert.match(doc.querySelector('.qtmAccountOrder__totals').textContent,/Discounts already included/);});
 for(const layout of ['sidebar','horizontal','compact']){const h=await f.engine.parseAndRender(f.read('snippets/account-main-account-nav.liquid'),{layout,active:'orders',show_tracking:true,section:{settings:{orders_label:'My purchases'}}},{globals:{routes}}),d=f.dom(h);assert(!d.window.document.querySelector('a[href="/pages/order-tracking"]'));assert.match(d.window.document.querySelector('[aria-current]').textContent,/My purchases/);assert.equal(!!d.window.document.querySelector('details'),layout==='compact');d.window.close();cases++;}
 // Filters use exact native status tokens; sorting/counts remain independent and page-local.
 {const d=f.dom(await host('orders',{id:'a'})+await host('orders',{id:'b'})),w=d.window,doc=w.document;f.boot(w,['account-main-account-orders.js']);const [a,b]=doc.querySelectorAll('[data-qtm-account-orders]'),visible=root=>[...root.querySelectorAll('tbody tr')].filter(x=>!x.hidden);a.querySelector('[data-qtm-account-orders-filter="fulfilled"]').click();assert.equal(visible(a).length,1);assert.equal(visible(a)[0].dataset.orderStatus,'unpaid fulfilled');assert.equal(visible(b).length,3);a.querySelector('[data-qtm-account-orders-filter="paid"]').click();assert.equal(visible(a).length,2);a.querySelector('[data-qtm-account-orders-filter="partial"]').click();assert.equal(visible(a).length,1);a.querySelector('[data-qtm-account-orders-filter="all"]').click();const sort=a.querySelector('select');sort.value='highest';sort.dispatchEvent(new w.Event('change'));assert.equal(visible(a)[0].dataset.orderTotal,'3000');const input=a.querySelector('input[type="search"]');input.value='missing';input.dispatchEvent(new w.Event('input'));assert(a.querySelector('[data-qtm-account-orders-no-matches]').hidden===false);a.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert.equal(visible(a).length,3);assert(a.querySelector('[data-qtm-orders-controls]').hidden);a.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert(!a.querySelector('[data-qtm-orders-controls]').hidden);cases+=9;w.close();}
 // Native address forms remain complete without JS; enhanced country/province and deletion are scoped.
 {const d=f.dom(await host('addresses',{id:'a'})+await host('addresses',{id:'b'})),w=d.window,doc=w.document;assert.equal(new Set([...doc.querySelectorAll('[id]')].map(x=>x.id)).size,doc.querySelectorAll('[id]').length);for(const p of doc.querySelectorAll('[data-qtm-addresses-add-panel],[data-qtm-addresses-edit-panel]'))assert(!p.hidden);assert.equal(doc.querySelector('[data-qtm-address-province]').tagName,'INPUT');f.boot(w,['account-main-account-addresses.js']);const [a,b]=doc.querySelectorAll('[data-qtm-account-addresses]');a.querySelector('[data-qtm-addresses-add-toggle]').click();const panel=a.querySelector('[data-qtm-addresses-add-panel]');assert(!panel.hidden);assert(b.querySelector('[data-qtm-addresses-add-panel]').hidden);assert.equal(doc.activeElement.name,'address[first_name]');const country=panel.querySelector('[data-qtm-address-country]'),province=panel.querySelector('select[name="address[province]"]');assert(province);assert.equal(province.value,'ON');country.value='France';country.dispatchEvent(new w.Event('change'));assert(province.disabled);assert(!new w.FormData(country.form).has('address[province]'));country.value='Unknown';country.dispatchEvent(new w.Event('change'));assert(!panel.querySelector('[data-qtm-address-province]').disabled);let confirms=0;w.confirm=()=>{confirms++;return false;};const e=new w.Event('submit',{bubbles:true,cancelable:true});a.querySelector('[data-qtm-address-delete-form]').dispatchEvent(e);assert(e.defaultPrevented);assert.equal(confirms,1);a.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));a.querySelector('[data-qtm-address-delete-form]').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));assert.equal(confirms,2);a.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(!panel.hidden);assert(!panel.querySelector('[data-qtm-address-province]').disabled);a.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert(panel.querySelector('select[name="address[province]"]')===null);cases+=12;w.close();}
 for(const provider of ['', 'javascript:bad()', '//outside.test', 'https://provider.test/track/{order}?email={email}#state', '/apps/track?store=one']){const d=f.dom(await host('order-tracking',{settings:{provider_url:provider}})),w=d.window,doc=w.document,root=doc.querySelector('[data-qtm-order-tracking]'),form=root.querySelector('form'),calls=[],location={origin:'https://shop.test',assign:url=>calls.push(url)};assert(form.hidden);const source=f.read('assets/account-main-order-tracking.js');w.Function('location',source)(location);doc.dispatchEvent(new w.Event('DOMContentLoaded'));w.Function('location',source)(location);const valid=provider.startsWith('https:')||provider.startsWith('/apps/');assert.equal(form.hidden,!valid);assert.match(root.textContent,/not the status of an order/);assert.equal(root.querySelector('[data-qtm-tracking-status-badge]'),null);assert.equal(root.querySelector('.is-active'),null);if(valid){form.elements.order_number.value='#A & B';form.elements.email.value='a+b@example.test';form.elements.tracking_number.value='T/1';form.dispatchEvent(new w.Event('submit',{cancelable:true}));assert.equal(calls.length,1);const url=new URL(calls[0]);assert.equal(url.searchParams.get('email'),'a+b@example.test');if(provider.includes('{order}'))assert.equal(decodeURIComponent(url.pathname),'/track/#A & B');else{assert.equal(url.searchParams.get('store'),'one');assert.equal(url.searchParams.get('order'),'#A & B');}root.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(form.hidden);root.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert(!form.hidden);}cases+=3;w.close();}
 for(const name of [...names,'nav']){const css=f.read('assets/account-main-account-'+name+'.css');postcss.parse(css);assert.doesNotMatch(css,/var\(--font-heading\)/);assert.doesNotMatch(css,/{[{%]|background: currentColor;\s*color: #fff/);if(name!=='nav')assert.match(css,/prefers-reduced-motion/);cases++;}
 console.log('PASS '+cases+' account page/native data/settings/guest/escaping/navigation/CSS and exact status filtering, sorting, address/province/delete/lifecycle, truthful provider redirect cases. Native form/pagination/navigation adapters are not Shopify/browser/AT certification.');
})().catch(e=>{console.error(e);process.exit(1)});
