const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');let cases=0;
const names=['activate','reset-password','register','login'];
const roots={activate:'QtmAccountMainActivate-', 'reset-password':'QtmAccountMainResetPassword-', register:'QtmAccountMainRegister-', login:'QtmAccountMainLogin-'};
const types={activate:'activate_customer_password','reset-password':'reset_customer_password',register:'create_customer',login:'customer_login'};
const routes={account_login_url:'/fr/account/login',account_register_url:'/fr/account/register',root_url:'/fr/'};
async function html(name,opts={}){return f.host('account-main-account-'+name,{globals:{routes},...opts})}
async function inspect(name,opts,fn){const h=await html(name,opts),d=f.dom(h);try{assert.doesNotMatch(h,/Liquid error|NaN|undefined/);fn(d.window.document,d.window,h);cases++}finally{d.window.close()}}
(async()=>{
 for(const name of names){
  await inspect(name,{},doc=>{const fs=[...doc.querySelectorAll('form')];assert.deepEqual(fs.map(x=>x.dataset.platformForm),name==='login'?['customer_login','recover_customer_password']:[types[name]]);assert(fs.every(form=>!form.noValidate));assert.equal(doc.querySelector('template'),null);for(const label of doc.querySelectorAll('label[for]'))assert(doc.getElementById(label.htmlFor));assert.equal(new Set([...doc.querySelectorAll('[id]')].map(x=>x.id)).size,doc.querySelectorAll('[id]').length);for(const button of doc.querySelectorAll('button[type="button"]'))assert(button.hidden);if(name==='activate'){const decline=doc.querySelector('[name="decline"]');assert(decline.formNoValidate);assert.equal(decline.value,'1');assert.equal(decline.form.querySelector('[type="password"]').required,true)}});
  const schema=f.unpack('account-main-account-'+name).schema;
  for(const st of schema.settings){for(const value of st.options?.map(x=>x.value)||(st.type==='range'?[st.min,st.max]:st.type==='checkbox'?[false,true]:[]))await inspect(name,{settings:{[st.id]:value}},(doc,w,h)=>{assert(doc.querySelector('form'));if(st.id==='show_password_toggle')assert.equal(doc.querySelectorAll('button[aria-pressed]').length,name==='activate'||name==='reset-password'?(value?2:0):(value?1:0));if(st.id==='recover_display')assert.equal(doc.querySelectorAll('form').length,2);if(st.id==='card_radius')assert(h.includes(': '+value+'px;'))})}
  await inspect(name,{settings:{heading:'<img src=x onerror=bad()>',subheading:'<safe>',card_background:'#000000'},globals:{routes,settings:{text_base:'#ffffff'},form:{email:'" autofocus data-bad="1',first_name:'<name>',last_name:'Last',errors:{email:'bad'}}}},(doc,w,h)=>{assert.equal(doc.querySelector('[onerror],[data-bad]'),null);assert.match(doc.querySelector('h1').textContent,/<img/);for(const input of doc.querySelectorAll('input[aria-describedby]'))assert(doc.getElementById(input.getAttribute('aria-describedby')));assert.match(doc.getElementById(roots[name]+'one').getAttribute('style'),/foreground: #ffffff|card-fg: #ffffff/)});
 }
 for(const name of names){const h=await html(name,{id:'one'})+await html(name,{id:'two'}),d=f.dom(h),w=d.window,doc=w.document;try{const source=f.read('assets/account-main-account-'+name+'.js');w.eval(source);doc.dispatchEvent(new w.Event('DOMContentLoaded'));w.eval(source);const first=doc.getElementById(roots[name]+'one'),second=doc.getElementById(roots[name]+'two');const a=first.querySelector('button[aria-pressed]'),b=second.querySelector('button[aria-pressed]');assert(!a.hidden);assert(!b.hidden);a.click();assert.equal(a.getAttribute('aria-pressed'),'true');assert.equal(b.getAttribute('aria-pressed'),'false');assert.equal(doc.getElementById(a.getAttribute('aria-controls')).type,'text');first.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));a.click();assert.equal(a.getAttribute('aria-pressed'),'false');a.click();first.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(a.hidden);assert.equal(doc.getElementById(a.getAttribute('aria-controls')).type,'password');assert(!b.hidden);first.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert(!a.hidden);a.click();assert.equal(a.getAttribute('aria-pressed'),'true');cases+=6;}finally{d.window.close()}}
 for(const mode of ['inline','toggle','panel']){const d=f.dom(await html('login',{settings:{recover_display:mode,show_password_text:"Show ' <text>",hide_password_text:"Hide ' <text>"}})),w=d.window,doc=w.document;try{const root=doc.querySelector('[data-account-main-account-login]'),login=root.querySelector('[data-account-main-account-login-panel="login"]'),recover=root.querySelector('[data-account-main-account-login-panel="recover"]')||root.querySelector('[data-account-main-account-login-recover-inline]');assert(!recover.hidden,'native recovery is visible without JS');assert(!recover.classList.contains('is-hidden'));w.eval(f.read('assets/account-main-account-login.js'));doc.dispatchEvent(new w.Event('DOMContentLoaded'));assert.equal(recover.hidden,mode!=='inline');if(mode!=='inline'){const trigger=root.querySelector('[data-account-main-account-login-recover-trigger]');trigger.click();assert(!recover.hidden);assert.equal(trigger.getAttribute('aria-expanded'),'true');assert.equal(doc.activeElement.name,'email');assert.equal(login.hidden,mode==='panel');if(mode==='panel'){root.querySelector('[data-account-main-account-login-login-trigger]').click();assert(recover.hidden);assert(!login.hidden);assert.equal(doc.activeElement,trigger)}}const toggle=root.querySelector('button[aria-pressed]');toggle.click();assert.equal(toggle.querySelector('span').textContent,"Hide ' <text>");cases+=4;}finally{d.window.close()}}
 // Simulated per-form Shopify status responses stay visible after enhancement.
 for(const role of ['status','alert']){const d=f.dom(await html('login',{settings:{recover_display:'panel'}})),w=d.window,doc=w.document;try{const recover=doc.querySelector('[data-account-main-account-login-panel="recover"]'),message=doc.createElement('div');message.role=role;message.tabIndex=-1;recover.prepend(message);w.eval(f.read('assets/account-main-account-login.js'));doc.dispatchEvent(new w.Event('DOMContentLoaded'));assert(!recover.hidden);assert(doc.querySelector('[data-account-main-account-login-panel="login"]').hidden);cases++}finally{d.window.close()}}
 for(const name of names){const file=name==='login'?'assets/account-main-account.css':'assets/account-main-account-'+name+'.css',css=f.read(file),ast=postcss.parse(css);let motion=false,solid=false;ast.walkAtRules('media',x=>{if(x.params.includes('prefers-reduced-motion'))motion=true});ast.walkRules(rule=>{if(rule.selector.endsWith('__button--solid')){const props=Object.fromEntries(rule.nodes.map(d=>[d.prop,d.value]));assert.equal(props.background,'var(--c-primary,#111)');assert.equal(props.color,'var(--c-oncolor,#fff)');solid=true;}});assert(motion&&solid);assert.match(css,/\[hidden\]\{display:none!important\}/);assert.doesNotMatch(css,/rgb\(var\(--color-background|border-radius: calc/);cases++;}
 console.log('PASS '+cases+' legacy account auth settings/presets/native forms/decline/escaped values/unique recovery/labels/surface contrast, independent password/panel/duplicate boot/unload/reload and CSS cases. Platform forms, native account services and browser pixels/AT remain live acceptance.');
})().catch(e=>{console.error(e);process.exit(1)});
