const fs=require('node:fs'),assert=require('node:assert/strict'),{Liquid}=require('liquidjs'),{JSDOM}=require('jsdom');
const read=p=>fs.readFileSync(p,'utf8'),defaults=fields=>Object.fromEntries(fields.filter(f=>f.id).map(f=>[f.id,f.default??null]));
const source=read('sections/main-collection-list.liquid'),schema=JSON.parse(source.split('{% schema %}')[1].split('{% endschema %}')[0]);
const engine=new Liquid({root:'snippets',extname:'.liquid'});engine.registerFilter('asset_url',p=>'/assets/'+p);engine.registerFilter('stylesheet_tag',p=>`<link rel="stylesheet" href="${p}">`);engine.registerFilter('image_url',i=>{assert(i);return '/image.jpg'});engine.registerFilter('placeholder_svg_tag',()=>'<svg class="placeholder"></svg>');
const collections=[0,1,2,3].map(i=>({id:i+1,url:'/collections/'+i,title:'Collection <'+i+'>',description:'<b>Details</b> & more',products_count:i,image:{width:1000,height:800,alt:'Collection image'}}));
const blocks=collections.map((c,i)=>({id:'b'+i,type:'collection',settings:{...defaults(schema.blocks[0].settings),collection:c}}));
const render=(id,overrides={},items=blocks,all=collections,page='list-collections')=>engine.parseAndRender(source.split('{% schema %}')[0],{section:{id,settings:{...defaults(schema.settings),...overrides},blocks:items},collections:all,request:{page_type:page}});
(async()=>{
 for(const layout of ['grid','carousel'])for(const source_mode of ['manual','all']){
  const d=new JSDOM(await render('one',{layout,source_mode,max_items:2,page_heading:true,show_count:true,show_description:true,title:'Shop <collections>'}));const doc=d.window.document;
  assert.equal(doc.querySelectorAll('.qcl-card').length,source_mode==='all'?2:4,'automatic limit is independent of manual blocks');assert.equal(doc.querySelectorAll('h1').length,1);assert.equal(doc.querySelectorAll('h2').length,0);assert(doc.querySelector('h1').closest('.qcl__inner'));assert.equal(doc.querySelector('.qcl-card__title').textContent,'Collection <0>');assert.equal(doc.querySelectorAll('[role="button"]').length,0);assert.equal(doc.querySelectorAll('.qcl-card__desc').length,source_mode==='all'?2:4);d.window.close();
 }
 const empty=new JSDOM(await render('empty',{page_heading:true},[{id:'empty',type:'collection',settings:{collection:null}}]));assert(empty.window.document.querySelector('h1'));assert(!empty.window.document.querySelector('a'));empty.window.close();
 const notPage=new JSDOM(await render('home',{page_heading:true},blocks,collections,'index'));assert(!notPage.window.document.querySelector('h1'));assert(notPage.window.document.querySelector('h2'));notPage.window.close();
 assert.equal((await engine.renderFile('collection-list-card',{s:defaults(schema.settings),c:null})).trim(),'');
 for(const ratio of ['adapt','square','landscape','portrait']){const d=new JSDOM(await render('ratio',{image_ratio:ratio,show_button:false,show_title:false},[{...blocks[0],settings:{...blocks[0].settings,image_override:{width:600,height:600,alt:'Override'},title_override:'Override <title>'}}]));assert.equal(d.window.document.querySelector('.qcl-card__link').getAttribute('aria-label'),'Override <title>');assert.equal(d.window.document.querySelector('img').alt,'Override');assert(!d.window.document.querySelector('.qcl-card__btn'));d.window.close();}
 const html=await render('one',{layout:'carousel'})+await render('two',{layout:'carousel'}),dom=new JSDOM(html,{runScripts:'outside-only'}),w=dom.window,roots=[...w.document.querySelectorAll('[data-qcl]')];
 const motion=new w.EventTarget();motion.matches=false;w.matchMedia=()=>motion;const observers=[];w.ResizeObserver=class{constructor(fn){this.fn=fn;observers.push(this)}observe(){}disconnect(){this.closed=true}};
 let width=300;const moves=[];
 roots.forEach((r,i)=>{const c=r.querySelector('[data-qcl-carousel]');c.style.direction=i?'rtl':'ltr';r.querySelector('.qcl__track').style.columnGap='16px';Object.defineProperties(c,{clientWidth:{get:()=>width},scrollWidth:{get:()=>900}});c.getBoundingClientRect=()=>({left:0,right:300});c.scrollTo=options=>{moves.push([i,options]);c.scrollLeft=options.left;c.dispatchEvent(new w.Event('scroll'))};r.querySelectorAll('.qcl__item').forEach((item,n)=>item.getBoundingClientRect=()=>({width:200,left:n*216,right:300-n*216}));});
 const script=read('assets/section-collection-list.js');w.eval(script);w.eval(script);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));assert.equal(observers.length,2);
 roots.forEach(r=>assert(r.querySelector('[data-qcl-prev]').disabled));roots[0].querySelector('[data-qcl-next]').click();assert.equal(moves.length,1,'duplicate script cannot double-bind');assert.equal(moves[0][1].left,216);assert.equal(moves[0][1].behavior,'smooth');
 motion.matches=true;roots[1].querySelector('[data-qcl-next]').click();assert.equal(moves[1][1].left,-216);assert.equal(moves[1][1].behavior,'auto');assert(!roots[1].querySelector('[data-qcl-prev]').disabled);
 roots[0].dispatchEvent(new w.CustomEvent('shopify:block:select',{bubbles:true,detail:{blockId:'b3'}}));assert.equal(moves.at(-1)[1].left,600,'editor selection scrolls to bounded destination');assert(roots[0].querySelector('[data-qcl-next]').disabled);
 width=1000;observers[0].fn();assert(roots[0].querySelector('[data-qcl-prev]').disabled);assert(roots[0].querySelector('[data-qcl-next]').disabled);
 roots[0].dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(observers[0].closed);assert(roots[0].querySelector('[data-qcl-next]').hidden);const before=moves.length;roots[0].querySelector('[data-qcl-next]').click();assert.equal(moves.length,before);
 width=300;roots[0].dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert.equal(observers.length,3);assert(!roots[0].querySelector('[data-qcl-next]').hidden);dom.window.close();
 for(const preset of schema.presets)await render('preset',preset.settings||{},preset.blocks.map((b,i)=>({id:'preset'+i,...b,settings:{...defaults(schema.blocks[0].settings),...b.settings}})));
 console.log('PASS Collection List: actual manual/automatic collections, auto limits, empty/preset states, heading semantics, image/title overrides, display controls, two instances, duplicate boot, RTL/reduced-motion scrolling, resize bounds and editor selection/unload/reload. Live Shopify/browser acceptance pending.');
})().catch(e=>{console.error(e);process.exitCode=1});
