const fs=require('node:fs'),assert=require('node:assert/strict'),{Liquid}=require('liquidjs'),{JSDOM}=require('jsdom');
const src=fs.readFileSync('sections/call-to-action-collection.liquid','utf8'),schema=JSON.parse(src.split('{% schema %}')[1].split('{% endschema %}')[0]);
const defaults=fields=>Object.fromEntries(fields.filter(f=>f.id).map(f=>[f.id,f.default??null]));
const e=new Liquid();e.registerFilter('image_url',i=>'/'+i.name+'.jpg');e.registerFilter('image_tag',url=>`<img src="${url}" width="600" height="400" alt="">`);
const col={url:'/collections/a?x=1&y=2',title:'Title <safe>',all_products_count:2,featured_image:{name:'collection'},products:[{featured_image:{name:'product'}}]};
const block={id:'card',type:'collection_card',shopify_attributes:'data-editor="card"',settings:{...defaults(schema.blocks[0].settings),collection:col}};
const render=(settings={},blocks=[block],id='one',editor=false)=>e.parseAndRender(src.split('{% schema %}')[0],{section:{id,settings:{...defaults(schema.settings),...settings},blocks},settings:{},request:{design_mode:editor}});
(async()=>{
 for(const layout of ['grid','masonry','grid_overlay','masonry_overlay'])for(const card_cta_style of ['none','button','text-link']){
  const d=new JSDOM(await render({layout,card_cta_style})),doc=d.window.document;assert.equal(doc.querySelectorAll('a').length,1);assert(!doc.querySelector('a a'));assert(!doc.querySelector('[role="link"]'));assert(!doc.querySelector('script'));assert.equal(doc.querySelectorAll('h3').length,1);assert.equal(doc.querySelector('h3').textContent,'Title <safe>');assert.equal(doc.querySelector('a').getAttribute('href'),col.url);assert.equal(doc.querySelectorAll('.q-cta').length,card_cta_style==='none'?0:1);assert.equal(doc.querySelectorAll('.q-onimg-wrap').length,layout.includes('overlay')?1:0);assert.equal(doc.querySelectorAll('.q-text').length,layout.includes('overlay')?0:1);assert(doc.querySelector('[data-editor]'));d.window.close();
 }
 for(const [image_source,custom_image,expected] of [['collection',null,'collection'],['first_product',null,'product'],['first_product',{name:'custom'},'custom']]){const d=new JSDOM(await render({image_source},[{...block,settings:{...block.settings,custom_image}}]));assert.equal(d.window.document.querySelector('img').getAttribute('src'),'/'+expected+'.jpg');d.window.close();}
 const fallback=new JSDOM(await render({image_source:'first_product'},[{...block,settings:{...block.settings,collection:{...col,products:[]}}}]));assert.equal(fallback.window.document.querySelector('img').getAttribute('src'),'/collection.jpg');fallback.window.close();
 const empty=new JSDOM(await render({},[{...block,settings:{collection:null}}]));assert(!empty.window.document.querySelector('a'));empty.window.close();
 const hidden=new JSDOM(await render({show_product_count:false},[{...block,settings:{...block.settings,cta_label:''}}]));assert(!hidden.window.document.querySelector('.q-count'));assert(!hidden.window.document.querySelector('.q-cta'));hidden.window.close();
 const gaps=[];for(const gap_scale of ['xs','sm','md','lg']){const d=new JSDOM(await render({gap_scale}));gaps.push(d.window.document.querySelector('section').style.getPropertyValue('--q-gap'));d.window.close();}assert.equal(new Set(gaps).size,4);assert(!src.includes('--q-gap: var(--q-gap'));
 for(const f of schema.settings){const values=f.options?.map(o=>o.value)||(f.type==='range'?[f.min,f.max]:f.type==='checkbox'?[false,true]:[]);for(const v of values)await render({[f.id]:v});}
 for(const preset of schema.presets)await render(preset.settings,preset.blocks.map((b,i)=>({id:'p'+i,...b,settings:{...defaults(schema.blocks[0].settings),...b.settings}})));
 const both=new JSDOM(await render({},[block],'one')+await render({},[block],'two'));const ids=[...both.window.document.querySelectorAll('[id]')].map(n=>n.id);assert.equal(new Set(ids).size,ids.length);both.window.close();
 for(const qty of [0,1,2]){const dom=new JSDOM(await render({},[{...block,settings:{...block.settings,collection:{...col,all_products_count:qty}}}]));assert.equal(dom.window.document.querySelector('.q-count').textContent,qty===1?'1 item':qty+' items');dom.window.close();}
 const zero=new JSDOM(await render({overlay_opacity:0,section_overlay_style:'solid',section_overlay_opacity:0,layout:'grid_overlay'}));assert.equal(zero.window.document.querySelector('section').style.getPropertyValue('--q-overlay-op').trim(),'0');assert.equal(zero.window.document.querySelector('.q-bg-overlay').style.opacity,'0');assert(!zero.window.document.querySelector('.q-media--placeholder .q-ph-title'));zero.window.close();
 const auto=new JSDOM(await render({image_ratio:'auto'},[{...block,settings:{...block.settings,custom_image:{name:'portrait',aspect_ratio:0.5}}}]));assert.equal(auto.window.document.querySelector('.q-media').style.aspectRatio,'0.5');auto.window.close();
 const scoped=new JSDOM(await render());function checkRules(rules){for(const r of rules){if(r.selectorText)for(const selector of r.selectorText.split(','))assert(selector.trim().startsWith('#section-one'),selector);if(r.cssRules)checkRules(r.cssRules)}}checkRules(scoped.window.document.querySelector('style').sheet.cssRules);scoped.window.close();
 assert((await render({},[],'empty',true)).includes('Select collections'));assert(!(await render({},[],'empty',false)).includes('Select collections'));
 assert(src.includes('prefers-reduced-motion'));assert(src.includes('var(--c-primary'));assert(!src.includes('.mh-M{grid-row'));
 console.log('PASS Collection CTA: four layouts, three CTA modes, native single links without JS, safe text, manual/product/collection image precedence and fallback, blank resources/labels, false count, distinct gaps, all select/range/checkbox inputs, four presets and two-instance identities. Live CSS/browser/editor acceptance pending.');
})().catch(err=>{console.error(err);process.exitCode=1});
