const assert=require('node:assert/strict'),f=require('./support/commerce.cjs');
const name='interactive-content-helper-predictive-search',routes={root_url:'/fr/',search_url:'/fr/search',predictive_search_url:'/fr/search/suggest'};
const resources={products:[{...f.product,price:1900,collections:[{handle:'selected'}]},{...f.product,id:2,title:'Second product',url:'/fr/products/second',price:0,collections:[]}],collections:[{title:'Collection <safe>',url:'/fr/collections/one'}],articles:[{title:'Article <safe>',url:'/fr/blogs/news/one',image:f.photo()}],pages:[{title:'Page <safe>',url:'/fr/pages/one'}]};
const markup=(settings={},id='host',result=null)=>f.render(name,{id,settings,data:{routes,predictive_search:result?{performed:true,terms:'Query <safe>',resources:result}:{performed:false}}});
function inspect(html,fn){const d=f.dom(html);try{fn(d.window.document)}finally{d.window.close()}}
function harness(html){const d=f.dom(html),w=d.window,timers=new Map(),requests=[];let serial=0;
 w.setTimeout=(fn,delay)=>{timers.set(++serial,{fn,delay});return serial;};w.clearTimeout=id=>timers.delete(id);
 w.fetch=(url,opts)=>new Promise((resolve,reject)=>requests.push({url:new URL(url),...opts,resolve,reject}));
 f.boot(w,['interactive-content-search.js']);
 return{d,w,requests,timers,type(value,root=w.document){const input=root.querySelector('input[type=search]');input.value=value;input.dispatchEvent(new w.Event('input',{bubbles:true}));return input;},async tick(){const active=[...timers].filter(([,x])=>x.delay<10000);active.forEach(([id,x])=>{timers.delete(id);x.fn();});await f.drain();},async answer(req,html){req.resolve({ok:true,text:async()=>'<div id="shopify-section-response">'+html+'</div>'});await f.drain();}};
}
(async()=>{
 for(const preset of f.unpack(name).schema.presets)inspect(await markup(preset.settings),doc=>assert.ok(doc.querySelector('form')));
 for(const s of f.unpack(name).schema.settings){const values=s.options?.map(o=>o.value)||(s.type==='range'?[s.min,s.max]:s.type==='checkbox'?[false,true]:[]);for(const value of values)inspect(await markup({[s.id]:value}),doc=>{assert.ok(doc.querySelector('form'));assert.doesNotMatch(doc.body.innerHTML,/Liquid error|NaN|undefined/);});}
 for(const scope of ['all','products_only','articles_only','pages_only'])for(const layout of ['cards','rows','compact','media']){
  const settings={search_scope:scope,panel_layout:layout,limit_products:1};
  inspect(await markup(settings),doc=>{assert.equal(doc.querySelector('form').getAttribute('action'),'/fr/search');assert.equal(doc.querySelector('[role=combobox]').tagName,'INPUT');assert.equal(doc.querySelectorAll('[role=combobox]').length,1);assert.equal(doc.querySelector('[name=type]')?.value,scope==='all'?undefined:scope.split('_')[0].replace(/s$/,''));assert.equal(doc.querySelector('[data-qps-chip]').tagName,'A');});
  const html=await markup(settings,'host',resources);inspect(html,doc=>{assert.equal(doc.querySelector('form,section,input,script,[role=option]'),null);assert.equal(doc.querySelectorAll('.q-ps__group').length,scope==='all'?4:1);assert.equal(doc.querySelector('[data-qps-render]').dataset.qpsLayout,layout);assert.equal(doc.querySelectorAll('.q-ps__viewall').length,1);assert.equal(new URL(doc.querySelector('.q-ps__viewall').href).pathname,'/fr/search');});
  const h=harness(await markup(settings));h.type('term');await h.tick();assert.equal(h.requests.length,1);const url=h.requests[0].url;assert.equal(url.pathname,'/fr/search/suggest');assert.equal(url.searchParams.get('section_id'),'host');assert.equal(url.searchParams.get('resources[type]'),scope==='all'?'product,collection,article,page':scope.split('_')[0].replace(/s$/,''));assert.equal(url.searchParams.get('resources[limit_scope]'),'each');assert.equal(url.searchParams.has('qps_scope'),false);assert.equal(url.searchParams.getAll('resources[type]').length,1);await h.answer(h.requests[0],html);assert.equal(h.w.document.querySelector('[data-qps-panel]').hidden,false);assert.equal(h.w.document.querySelector('#shopify-section-response'),null);h.d.window.close();
 }
 inspect(await markup({limit_collections:0,limit_articles:0,limit_pages:0},'host',resources),doc=>assert.equal(doc.querySelectorAll('.q-ps__group').length,1));
 const restricted={search_scope:'products_only',panel_layout:'media',restrict_to_collection:{handle:'selected',title:'Selected <safe>'}};
 inspect(await markup(restricted,'host',resources),doc=>{assert.equal(doc.querySelectorAll('.q-ps__row--product').length,1);assert.equal(doc.querySelector('.q-ps__row-title').textContent,f.product.title);});
 inspect(await markup({...restricted,restrict_to_collection:{handle:'missing'}},'host',resources),doc=>{assert.ok(doc.querySelector('.q-ps__empty'));assert.equal(doc.querySelector('.q-ps__group'),null);});
 inspect(await markup({show_popular_queries:false,show_recent_searches:false,popular_queries:'',heading:'',subheading:''}),doc=>assert.equal(doc.querySelector('header,[data-qps-chips],[data-qps-recent]'),null));
 const empty=await markup({no_results_text:'Nothing <safe>'},'host',{});inspect(empty,doc=>assert.match(doc.querySelector('.q-ps__empty-title').textContent,/Nothing <safe>.*Query <safe>/));
 const response=await markup({panel_layout:'rows'},'host',resources);
 let h=harness(await markup({panel_layout:'rows',max_suggestions:16,limit_products:12}));let input=h.type('first');await h.tick();const first=h.requests.at(-1);assert.equal(first.url.searchParams.get('resources[limit]'),'10');h.type('second');assert(first.signal.aborted);await h.tick();const second=h.requests.at(-1);await h.answer(second,response);await h.answer(first,empty);assert.equal(h.w.document.querySelector('.q-ps__empty'),null);
 input.focus();await h.tick();await h.answer(h.requests.at(-1),response);
 input.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}));const link=h.w.document.activeElement;assert.equal(link.tagName,'A');link.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}));assert.notEqual(h.w.document.activeElement,link);h.w.document.activeElement.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(h.w.document.activeElement,input);assert.equal(h.w.document.querySelector('[data-qps-panel]').hidden,true);assert.equal(h.timers.size,0);
 h.type('late');await h.tick();const late=h.requests.at(-1);input.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert(late.signal.aborted);await h.answer(late,response);assert.equal(h.w.document.querySelector('[data-qps-panel]').hidden,true);
 input.dispatchEvent(new h.w.CompositionEvent('compositionstart'));h.type('compose');await h.tick();const count=h.requests.length;input.dispatchEvent(new h.w.CompositionEvent('compositionend'));await h.tick();assert.equal(h.requests.length,count+1);h.requests.at(-1).resolve({ok:false});await f.drain();assert.match(h.w.document.querySelector('[role=status]').textContent,/unavailable/);assert.equal(input.hasAttribute('aria-busy'),false);
 h.type('invalid response');await h.tick();await h.answer(h.requests.at(-1),'<form>Wrong response</form>');assert.equal(h.w.document.querySelectorAll('form').length,1);assert.equal(h.w.document.querySelector('[data-qps-panel]').hidden,true);
 h.type('timeout');await h.tick();[...h.timers.values()].forEach(x=>x.fn());assert(h.requests.at(-1).signal.aborted);assert.equal(h.timers.size,0);h.d.window.close();
 h=harness(await markup({show_recent_searches:true},'one')+await markup({open_on_focus:false,close_on_escape:false},'two'));h.w.localStorage.setItem('qps_recent_terms_v1',JSON.stringify([42,null,'Saved <safe>']));input=h.w.document.querySelector('input');input.focus();assert.equal(h.w.document.querySelectorAll('[data-qps-recent-chips] a').length,1);assert.equal(h.w.document.querySelector('[data-qps-recent-chips] a').textContent,'Saved <safe>');
 const roots=h.w.document.querySelectorAll('[data-qps-host]');h.type('one',roots[0]);h.type('two',roots[1]);await h.tick();assert.equal(h.requests.length,2);assert.deepEqual(h.requests.map(r=>r.url.searchParams.get('section_id')),['one','two']);const pending=h.requests[0];roots[0].dispatchEvent(new h.w.CustomEvent('shopify:section:unload',{bubbles:true}));assert(pending.signal.aborted);await h.answer(pending,response);assert(roots[0].querySelector('[data-qps-panel]').hidden);await h.answer(h.requests[1],response);assert.equal(roots[1].querySelector('[data-qps-panel]').hidden,false);h.type('unloaded',roots[0]);await h.tick();assert.equal(h.requests.length,2);roots[0].dispatchEvent(new h.w.CustomEvent('shopify:section:load',{bubbles:true}));h.type('reloaded',roots[0]);await h.tick();assert.equal(h.requests.length,3);h.d.window.close();
 console.log('PASS actual Content Search settings/presets, four scopes × four layouts, native locale forms/chips/typed links, host-specific section requests/limits/collection filtering/empty groups, rendered-fragment extraction, real keyboard focus, stale request rejection, Escape/IME/timeouts/failures, optional recent storage and independent disposable editor lifecycle. Live predictive API/settings/locale/AT acceptance remains queued.');
})().catch(error=>{console.error(error);process.exitCode=1;});
