const assert=require('node:assert/strict'),f=require('./support/commerce.cjs');
const NativeDate=Date;global.Date=class extends NativeDate{constructor(...args){super(...(args.length?args:['2026-09-20T15:00:00Z']))}static now(){return new NativeDate('2026-09-20T15:00:00Z').valueOf()}};
const sale='featured-content-sale-highlight',blog='featured-content-blog-spotlight';
const deal=(title,settings={})=>({type:'deal',settings:{title,...settings}});
const article=(id,tags=[])=>({id,handle:'post-'+id,title:'Story <safe> '+id,url:'/fr/blogs/news/post-'+id,tags,content:'<p>'+Array.from({length:40},(_,i)=>'word'+i).join(' ')+'</p>',excerpt_or_content:'<p>'+Array.from({length:40},(_,i)=>'word'+i).join(' ')+'</p>',published_at:'2026-09-01',author:'Author <safe>',image:f.photo()});
(async()=>{
 const deals=[deal('Expired',{end_date:'2026-09-19'}),deal('Future',{start_date:'2026-09-21'}),deal('Ends today',{end_date:'2026-09-20'}),deal('Starts today',{start_date:'2026-09-20'}),deal('Invalid date',{end_date:'bad-date'}),deal('Overflow')];
 let d=f.dom(await f.render(sale,{blocks:deals,settings:{mode:'cards',max_cards:3}})),doc=d.window.document;
 assert.deepEqual([...doc.querySelectorAll('.q-promo__title')].map(x=>x.textContent),['Ends today','Starts today','Invalid date']);assert.equal(doc.querySelectorAll('.q-promo__expiry').length,1,'end day remains visible after midnight; malformed date not shown');assert.match(doc.querySelector('.q-promo__expiry').textContent,/September/);d.window.close();
 d=f.dom(await f.render(sale,{blocks:deals,settings:{mode:'hero'}}));assert.equal(d.window.document.querySelectorAll('.q-promo').length,1);assert.equal(d.window.document.querySelector('.q-promo__title').textContent,'Ends today');d.window.close();
 assert.doesNotMatch(await f.render(sale,{blocks:deals.slice(0,2)}),/<section/);assert.match(await f.render(sale,{blocks:deals.slice(0,2),data:{request:{design_mode:true}}}),/No deals are active/);
 const hostile=deal('<img src=x onerror=bad>',{description:'<script>bad</script>',badge:'Badge <safe>',link:'/fr/collections/all?x="',cta_label:'Open <safe>',product:{...f.product,requires_selling_plan:true},bg_color:'#123456',fg_color:'#ffffff'});
 d=f.dom(await f.render(sale,{blocks:[hostile],settings:{heading:'Offers <safe>',kicker:'Kicker <safe>',background_mode:'per_deal',product_enable_quick_add:true}}));doc=d.window.document;assert.equal(doc.querySelector('.q-promo__title').textContent,hostile.settings.title);assert.equal(doc.querySelector('[onerror],.q-promo__content script'),null);assert.equal(doc.querySelector('.q-promo__btn').textContent,'Open <safe>');assert.equal(doc.querySelector('form[action*="cart/add"]'),null,'required subscription uses product options');assert.match(doc.querySelector('.q-promo').getAttribute('style'),/--q-promo-bg: #123456/);d.window.close();
 const products=[article(1,['featured']),article(2,[]),article(3,['featured'])],blocks=products.map(a=>({type:'article',settings:{article:a}}));
 for(const layout_style of ['featured','grid','scroll']){d=f.dom(await f.render(blog,{blocks,settings:{layout_style,excerpt_words:10}}));doc=d.window.document;assert.equal(doc.querySelectorAll('.q-blogcard').length,3,'native article picker objects need no global articles lookup');assert.equal(doc.querySelectorAll('[data-editor-block]').length,3);assert.equal(doc.querySelector('.q-blogcard__title a').textContent,products[0].title);assert.doesNotMatch(doc.querySelector('.q-blogcard__excerpt').textContent,/<p>|word10/);assert.match(doc.querySelector('.q-blogcard__excerpt').textContent,/word9/);assert.match(doc.querySelector('.q-bhs').getAttribute('style'),/--q-bhs-title-lh: 1.2;/);assert.match(doc.querySelector('.q-bhs').getAttribute('style'),/--q-bhs-featured-split: 58;/);if(layout_style==='featured'){assert.equal(doc.querySelector('.q-bhs__featured .q-blogcard__link').textContent.trim(),'Read the story');assert.equal(doc.querySelectorAll('.q-bhs__supporting .q-blogcard').length,2);}if(layout_style==='scroll')assert.equal(doc.querySelector('.q-bhs__scroller').tabIndex,0);d.window.close();}
 d=f.dom(await f.render(blog,{blocks:blocks.slice(0,1)}));assert.ok(d.window.document.querySelector('.q-bhs__layout--single'));assert.equal(d.window.document.querySelector('.q-bhs__supporting'),null);d.window.close();
 d=f.dom(await f.render(blog,{settings:{source_mode:'auto',blog:{url:'/fr/blogs/news',articles:products},tag_filter:'featured',auto_limit:2,layout_style:'grid',heading:'Heading <safe>'}}));doc=d.window.document;assert.deepEqual([...doc.querySelectorAll('.q-blogcard__title a')].map(x=>x.textContent),[products[0].title,products[2].title]);assert.equal(doc.querySelector('.q-bhs__viewAll').pathname,'/fr/blogs/news');d.window.close();
 d=f.dom(await f.render(blog,{blocks,settings:{show_header:false,show_image:false,show_author:false,show_date:false,show_tags:false,show_read_time:false,show_excerpt:false,cta_label_featured:'',cta_label_supporting:''}}));doc=d.window.document;assert.equal(doc.querySelector('.q-bhs__header,.q-blogcard__media,.q-blogcard__meta,.q-blogcard__excerpt,.q-blogcard__cta'),null);d.window.close();
 for(const name of [sale,blog]){const schema=f.unpack(name).schema;const validBlocks=name===sale?[hostile]:blocks;for(const setting of schema.settings.filter(s=>s.type==='select'))for(const option of setting.options)assert.doesNotMatch(await f.render(name,{blocks:validBlocks,settings:{[setting.id]:option.value}}),/Liquid error|NaN/);for(const preset of schema.presets)assert.doesNotMatch(await f.render(name,{blocks:preset.blocks,settings:preset.settings}),/Liquid error|NaN/);const html=await f.render(name,{id:'a',blocks:validBlocks})+await f.render(name,{id:'b',blocks:validBlocks});d=f.dom(html);const ids=[...d.window.document.querySelectorAll('[id]')].map(e=>e.id);assert.equal(new Set(ids).size,ids.length);d.window.close();}
 console.log('PASS Featured Deals/Blog: actual presets/select settings, inclusive/invalid/scheduled dates and editor empty state; escaped text, existing subscription/card destinations, native selected article objects, filtered limits, meaningful excerpts, all layouts, single article, false toggles and independent instances. Shopify date caching/browser acceptance queued.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{global.Date=NativeDate});
