const assert=require('node:assert/strict'),f=require('./support/forms.cjs');
const name='form-search',globals={shop:{currency:'USD'}};
const render=(opts={})=>f.host(name,{globals,...opts});
function inspect(html){const d=f.dom('<style>'+f.read('assets/forms-sections.css')+'</style>'+html),doc=d.window.document;
 const ids=[...doc.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size);
 for(const el of doc.querySelectorAll('[aria-describedby],[aria-controls]'))for(const attr of ['aria-describedby','aria-controls'])for(const id of (el.getAttribute(attr)||'').split(/\s+/).filter(Boolean))assert(doc.getElementById(id),id);
 for(const el of doc.querySelectorAll('label[for]'))assert(doc.getElementById(el.htmlFor));assert(!html.includes('NaN'));return d;
}
function harness(html){const d=inspect(html),w=d.window,timers=new Map(),requests=[];let serial=0;
 w.setTimeout=(fn,delay)=>{timers.set(++serial,{fn,delay});return serial;};w.clearTimeout=id=>timers.delete(id);
 w.fetch=(url,opts)=>new Promise((resolve,reject)=>requests.push({url:new URL(url),...opts,resolve,reject}));
 f.boot(w,['interactive-content-search.js','form-search.js','frontend-form-logic.js']);
 return{d,w,requests,timers,type(value,root=w.document){const input=root.querySelector('[name=q]');input.value=value;input.dispatchEvent(new w.Event('input',{bubbles:true}));return input;},async tick(){for(const[id,t]of [...timers].filter(([,t])=>t.delay<10000)){timers.delete(id);t.fn()}await f.drain()},async answer(req,html){req.resolve({ok:true,text:async()=>'<div class="shopify-section">'+html+'</div>'});await f.drain()}};
}
const resources={products:[{...f.product,title:'<Product>',price:1900},{...f.product,id:2,title:'Second',price:0}],collections:[{title:'<Collection>',url:'/fr/collections/one',image:f.photo()}],articles:[{title:'<Article>',url:'/fr/blogs/news/one',author:'<Author>',image:f.photo()}],pages:[{title:'<Page>',url:'/fr/pages/one'}]};
const response=(opts={})=>render({settings:{mode:'predictive',predictive_limit:1},data:{predictive_search:{performed:true,terms:'Query <safe>',resources}},...opts});
(async()=>{
 let cases=0;const {schema}=f.unpack(name);
 for(const preset of schema.presets){const d=inspect(await render({settings:preset.settings,blocks:preset.blocks})),doc=d.window.document;assert.equal(doc.querySelector('form').method,'get');assert.equal(doc.querySelector('form').getAttribute('action'),'/fr/search');assert(!doc.querySelector('form').noValidate);assert(!doc.querySelector('[data-q-form-host]'));d.window.close();cases++;}
 for(const s of schema.settings){const values=s.type==='select'?s.options.map(x=>x.value):s.type==='range'?[s.min,s.max]:s.type==='checkbox'?[true,false]:[];for(const value of values){const d=inspect(await render({settings:{[s.id]:value}}));assert(d.window.document.querySelector('form'));d.window.close();cases++;}}
 for(const mode of ['basic','finder','predictive'])for(const scope_default of ['all','product','collection','article','page'])for(const show_scope of [true,false]){
  const d=inspect(await render({settings:{mode,scope_default,show_scope}})),doc=d.window.document,form=doc.querySelector('form');const type=new d.window.FormData(form).get('type');assert.equal(type,['product','article','page'].includes(scope_default)?scope_default:'product,article,page');assert.equal(!!doc.querySelector('[role=combobox]'),mode==='predictive');if(mode!=='predictive')assert(!doc.querySelector('[data-qps-panel]'));d.window.close();cases++;
 }
 for(const [nav_target,target] of [['','/fr/search'],['/search','/fr/search'],['/pages/finder','/fr/pages/finder'],['/fr/pages/finder','/fr/pages/finder'],['/fr','/fr'],['https://evil.test/search','/fr/search'],['//evil.test','/fr/search'],['/\\evil.test','/fr/search'],['/search?evil=true','/fr/search'],['/search#x','/fr/search']]){const d=inspect(await render({settings:{nav_target}}));assert.equal(d.window.document.querySelector('form').getAttribute('action'),target);d.window.close();}
 let d=inspect(await render({id:'style',settings:{mode:'finder',heading:'<Heading>',kicker:'<Kicker>',subheading:'<Sub>',heading_level:'h2',help_text:'<Help>',aria_label:'"Search',anchor_id:'a:日本語[search]"',hide_on_mobile:true,hide_on_desktop:true,padding_x:0,padding_y:0,card_radius:0,card_shadow:0,overlay_type:'gradient',grad_angle:0,grad_start_opacity:0,grad_end_opacity:0},globals:{...globals,request:{design_mode:true},settings:{button_variant_default:'outline',text_base:'#ffffff',text_muted:'#ffffff',color_primary:'#ffffff',text_on_color:'#ffffff'}}})),doc=d.window.document,root=doc.querySelector('[data-q-form-search]');assert(root.classList.contains('q-form-scope-style'));assert.equal(root.id,'a:日本語[search]"');assert(!root.classList.contains('hide-mobile'));assert(!doc.querySelector('heading,kicker,sub,help'));assert.equal(doc.querySelector('h2').textContent,'<Heading>');assert(doc.querySelector('button.q-btn--outline'));const styles=doc.querySelectorAll('style')[1].textContent;assert.match(styles,/--q-pad-x:\s*0px/);assert.match(styles,/--q-card-shadow:\s*none/);assert.match(styles,/--q-btn-fg:\s*#000000/);assert(!styles.includes('#a:日本語'));assert.match(doc.querySelector('.q-overlay').getAttribute('style'),/0deg/);d.window.close();
 for(const side of ['left','right']){d=inspect(await render({settings:{template_style:'split',split_media_side:side,split_image:f.photo()}}));assert.equal(d.window.document.querySelector('.q-media-card img').alt,'Photo <safe>');d.window.close();}
 d=inspect(await render({settings:{template_style:'split',split_image:null}}));assert(!d.window.document.querySelector('.q-grid.split-left,.q-grid.split-right'));d.window.close();
 const finder={mode:'finder',enable_category:true,enable_tag:true,enable_price:true,category_label:'APAC category',category_options:'aa-1|Category <A>\nbb-2|Category B',tag_options:'new|New <tag>\ngift|Gift',price_options:'<50|Under $50\n50-150|$50–150\n150+|$150+\n0+|Free or more\n150-50|Bad order\n<script>|Bad band'};
 const saved={terms:'Query <safe>',filters:[{param_name:'filter.p.t.category',active_values:[{value:'bb-2'}]},{param_name:'filter.p.tag',active_values:[{value:'gift'}]},{type:'price_range',min_value:{value:5000},max_value:{value:15000}}]};
 d=inspect(await render({settings:finder,data:{search:saved}}));doc=d.window.document;const form=doc.querySelector('form'),data=new d.window.FormData(form);assert.equal(data.get('q'),'Query <safe>');assert.equal(data.get('filter.p.t.category'),'bb-2');assert.equal(data.get('filter.p.tag'),'gift');assert.equal(Number(data.get('filter.v.price.gte')),50);assert.equal(Number(data.get('filter.v.price.lte')),150);assert(!data.has('cat'));assert(!data.has('tag'));assert(!data.has('price'));assert(doc.querySelector('[data-price-shortcut]').hidden);assert.equal(doc.querySelector('label[for$="-category"]').textContent,'APAC category');assert(!doc.querySelector('tag,a category'));
 f.boot(d.window,['form-search.js','form-search.js']);const band=doc.querySelector('[data-price-band]'),min=doc.querySelector('[name="filter.v.price.gte"]'),max=doc.querySelector('[name="filter.v.price.lte"]');assert(!doc.querySelector('[data-price-shortcut]').hidden);assert(band.querySelector('[value="150-50"]').disabled);
 for(const[value,lo,hi]of [['<50','','49.99'],['50-150','50.00','150.00'],['150+','150.00',''],['0+','0.00',''],['','','']]){band.value=value;band.dispatchEvent(new d.window.Event('change',{bubbles:true}));assert.equal(min.value,lo);assert.equal(max.value,hi);}
 min.value='100';max.value='50';max.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert(max.validity.customError);max.value='101';max.dispatchEvent(new d.window.Event('input',{bubbles:true}));assert(!max.validity.customError);assert.equal(band.value,'');form.reset();await f.drain();assert.equal(Number(min.value),50);root=doc.querySelector('[data-q-form-search]');root.dispatchEvent(new d.window.Event('shopify:section:unload',{bubbles:true}));assert(doc.querySelector('[data-price-shortcut]').hidden);assert(!band.querySelector('[value="150-50"]').disabled);d.window.close();
 d=inspect(await render({settings:{...finder,category_options:'',tag_options:'',price_options:''}}));assert(!d.window.document.querySelector('[name="filter.p.t.category"],[name="filter.p.tag"]'));f.boot(d.window,['form-search.js']);assert(d.window.document.querySelector('[data-price-shortcut]').hidden);d.window.close();
 const quickLinks=[{type:'quick_link',settings:{label:'<Quick>',url:'/fr/pages/quick'}},{type:'quick_link',settings:{label:'Missing',url:''}}];
 d=inspect(await render({blocks:quickLinks}));assert.equal(d.window.document.querySelectorAll('.q-search-links a').length,1);assert.equal(d.window.document.querySelector('.q-search-links a').textContent,'<Quick>');d.window.close();
 const result=await response();d=f.dom(result);doc=d.window.document;assert(!doc.querySelector('form,section,input,script,style,[role=option]'));assert.equal(doc.querySelectorAll('.q-group').length,4);assert.equal(doc.querySelector('.q-item-sub').textContent,'$19.00');assert.equal(doc.querySelector('.q-item-title').textContent,'<Product>');assert(!doc.querySelector('product,collection,article,author,page'));d.window.close();
 d=f.dom(await response({settings:{predictive_sources:' PAGES ',predictive_limit:1},data:{predictive_search:{performed:true,terms:'missing',resources}}}));assert.equal(d.window.document.querySelectorAll('.q-group').length,1);assert.equal(d.window.document.querySelector('.q-group').dataset.type,'pages');d.window.close();
 d=f.dom(await response({blocks:quickLinks,data:{predictive_search:{performed:true,terms:'<none>',resources:{}}}}));assert.match(d.window.document.querySelector('.q-ps__empty').textContent,/<none>/);assert.equal(d.window.document.querySelectorAll('.q-items a').length,1);assert(!d.window.document.querySelector('none,quick'));d.window.close();
 let h=harness(await render({id:'one',settings:{mode:'predictive',predictive_limit:3}})+await render({id:'two',settings:{mode:'predictive',show_scope:false,scope_default:'page'}}));const roots=h.w.document.querySelectorAll('[data-qps-host]');let input=h.type('query',roots[0]);h.type('second',roots[1]);await h.tick();assert.equal(h.requests.length,2);let req=h.requests[0];assert.equal(req.url.pathname,'/fr/search/suggest');assert.equal(req.url.searchParams.get('section_id'),'one');assert.equal(req.url.searchParams.get('resources[type]'),'product,collection,article,page');assert.equal(req.url.searchParams.get('resources[limit]'),'3');assert.equal(req.url.searchParams.get('resources[limit_scope]'),'each');assert.equal(h.requests[1].url.searchParams.get('resources[type]'),'page');assert(!roots[0].querySelector('form').dataset.qValidateInit);
 const scope=roots[0].querySelector('[data-qps-scope]');scope.querySelector('[data-resource-type=collection]').selected=true;scope.dispatchEvent(new h.w.Event('change',{bubbles:true}));assert(req.signal.aborted);await h.tick();const collectionRequest=h.requests.at(-1);assert.equal(collectionRequest.url.searchParams.get('resources[type]'),'collection');await h.answer(req,result);assert(roots[0].querySelector('[data-qps-panel]').hidden);await h.answer(collectionRequest,result);assert(!roots[0].querySelector('[data-qps-panel]').hidden);const all=new URL(roots[0].querySelector('[data-qps-view-all]').href);assert.equal(all.searchParams.get('type'),'product,article,page');assert.equal(all.searchParams.get('q'),'query');input.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true,cancelable:true}));assert.equal(h.w.document.activeElement.tagName,'A');h.w.document.activeElement.dispatchEvent(new h.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true}));assert.equal(h.w.document.activeElement,input);assert(roots[0].querySelector('[data-qps-panel]').hidden);
 input.dispatchEvent(new h.w.CompositionEvent('compositionstart'));h.type('typing',roots[0]);const before=h.requests.length;await h.tick();assert.equal(h.requests.length,before);input.dispatchEvent(new h.w.CompositionEvent('compositionend'));await h.tick();assert.equal(h.requests.length,before+1);h.requests.at(-1).resolve({ok:false});await f.drain();assert.match(roots[0].querySelector('[data-qps-status]').textContent,/unavailable/);
 h.type('later',roots[0]);await h.tick();req=h.requests.at(-1);roots[0].dispatchEvent(new h.w.Event('shopify:section:unload',{bubbles:true}));assert(req.signal.aborted);await h.answer(req,result);assert(roots[0].querySelector('[data-qps-panel]').hidden);await h.answer(h.requests[1],result);assert(!roots[1].querySelector('[data-qps-panel]').hidden);roots[0].dispatchEvent(new h.w.Event('shopify:section:load',{bubbles:true}));h.type('again',roots[0]);await h.tick();assert(h.requests.length>before+1);h.d.window.close();
 console.log('PASS independent Site Search/Finder: '+cases+' preset/settings/scope cases; native localized GET/filter payloads, valid resource types, collection-suggestion fallback, native money/results/quick links, price shortcuts and no-JS ranges, safe copy/layout/visibility, scoped requests and keyboard/IME/failure/stale/editor lifecycle. Native API/filter administration/currency/AT acceptance queued.');
})().catch(e=>{console.error(e);process.exit(1)});
