const assert=require('node:assert/strict'),f=require('./support/forms.cjs');
(async()=>{
  const blocks=[f.field('a','text',{default_value:'<Saved>',required:true}),f.field('b','text'),f.field('mail','email',{name_attr:'email',required:false}),f.field('tel','tel',{default_value:'+44 12 ext 3'}),f.field('n','number',{default_value:'1.25'}),f.field('txt','textarea',{default_value:'Line 1\n<script>safe</script>'}),f.field('sel','select',{options:'one|One\r\ntwo|Two & <safe>\n\nthree|Three',default_value:'two',help_text:'Help <safe>'}),f.field('rad','radio',{options:'one|One\ntwo|Two',default_value:'two',required:true}),f.field('consent','consent',{default_value:'yes',required:true}),f.field('html','html',{html_content:'<p>Rich <strong>text</strong></p>'}),f.field('hidden','hidden',{default_value:'<kept>'}),f.field('file','file',{default_value:'never',accept:'.pdf'}),f.field('pw','password',{default_value:'never'}),f.field('cond','text',{condition_enable:true,condition_field:'a" ][',condition_operator:'equals',condition_value:'<literal>'})];
  let d=f.dom(await f.snippet('form-dispatch',{blocks})),doc=d.window.document,form=doc.querySelector('form');
  assert.equal(form.dataset.platformForm,'contact');assert.equal(form.getAttribute('data-shopify-captcha'),'true');assert(!form.noValidate);
  assert.equal(doc.querySelector('[type=email]').name,'contact[email]');assert(doc.querySelector('[type=email]').required);
  assert.equal(doc.getElementById('qf-one-a').name,'contact[field-a]');assert.equal(doc.getElementById('qf-one-b').name,'contact[field-b]');
  assert.equal(doc.getElementById('qf-one-a').value,'<Saved>');assert.equal(doc.querySelector('textarea').value,'Line 1\n<script>safe</script>');assert(!doc.querySelector('script'));
  assert.equal(doc.querySelector('select').options.length,4);assert.equal(doc.querySelector('select').value,'two');assert.equal(doc.querySelector('select').selectedOptions[0].textContent,'Two & <safe>');
  assert.equal(doc.querySelector('[type=radio]:checked').value,'two');assert.equal(doc.querySelectorAll('fieldset legend').length,1);assert(!doc.querySelector('[type=checkbox]').checked);
  assert.equal(doc.querySelector('[type=file]'),null);assert.equal(doc.querySelector('[type=password]'),null);assert.equal(doc.getElementById('qf-one-file').type,'url');assert.match(doc.getElementById('qf-one-file-file-help').textContent,/link/);assert(doc.querySelector('.q-html strong'));
  assert.equal(doc.querySelector('[data-cond]').dataset.condField,'a" ][');
  for(const el of doc.querySelectorAll('[aria-describedby]'))for(const id of el.getAttribute('aria-describedby').split(' '))assert(doc.getElementById(id),id);
  const ids=[...doc.querySelectorAll('[id]')].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);d.window.close();
  d=f.dom(await f.snippet('form-dispatch',{blocks:blocks.slice().reverse(),theme_settings:{button_variant_default:'outline'},settings:{destination:'shopify_customer',button_variant:'inherit'},eff_marketing_map_name:false,eff_marketing_double_opt_in:false}));doc=d.window.document;
  assert.equal(doc.querySelector('form').dataset.platformForm,'customer');assert(doc.querySelector('[name="contact[marketing_confirmation]"]').required);assert(!doc.querySelector('[name="contact[marketing_confirmation]"]').checked);assert.equal(doc.getElementById('qf-one-a').name,'contact[field-a]');assert(doc.querySelector('button.q-btn--outline'));
  assert.equal(doc.querySelector('[name="contact[marketing_map_name]"]').value,'false');assert.equal(doc.querySelector('[name="contact[marketing_double_opt_in]"]').value,'false');d.window.close();
  for(const endpoint of ['', 'https://', '//other.test/path', 'javascript:alert(1)', '/\\other.test/path']){d=f.dom(await f.snippet('form-dispatch',{settings:{destination:'custom_endpoint',endpoint_url:endpoint},globals:{request:{design_mode:true}}}));assert(!d.window.document.querySelector('form'),endpoint);assert.match(d.window.document.body.textContent,/Configure a valid/);d.window.close();}
  for(const endpoint of ['https://forms.example.test/submit','/apps/forms']){d=f.dom(await f.snippet('form-dispatch',{settings:{destination:'custom_endpoint',endpoint_url:endpoint,captcha_mode:'turnstile'},blocks}));form=d.window.document.querySelector('form');assert.equal(form.getAttribute('action'),endpoint);assert.equal(form.enctype,'multipart/form-data');assert(form.querySelector('[name="cf-turnstile-response"]'));assert.equal(form.querySelector('[type=email]').name,'email');assert.equal(form.querySelector('[type=file]').getAttribute('value'),null);assert.equal(form.querySelector('[type=password]').getAttribute('value'),null);d.window.close();}
  d=f.dom(await f.snippet('form-dispatch',{settings:{destination:'shopify_contact',captcha_mode:'recaptcha_v3',error_text:'<Bad>'},blocks:[f.field('email','email')],globals:{form:{errors:Object.assign(['email'],{email:'invalid'}),email:'returned@example.test'}}}));doc=d.window.document;
  assert(!doc.querySelector('[name="g-recaptcha-response"]'));assert(doc.querySelector('[role=alert] [data-platform-errors]'));assert.match(doc.querySelector('[role=alert]').textContent,/<Bad>/);assert.equal(doc.querySelector('[type=email]').value,'returned@example.test');assert.equal(doc.querySelector('[type=email]').getAttribute('aria-invalid'),'true');d.window.close();
  d=f.dom(await f.snippet('form-dispatch',{blocks:[],globals:{form:{'posted_successfully?':true}}}));assert(d.window.document.querySelector('[type=email][required][name="contact[email]"]'));assert.match(d.window.document.querySelector('[role=status]').textContent,/Thanks/);d.window.close();
  for(const name of ['call-to-action-quote-form','form-quote-full','form-compact','form-support-request']){d=f.dom(await f.host(name));assert(d.window.document.querySelector('form input[type=email][required]'),name);d.window.close();}
  console.log('PASS native form fields/routing: stable unique identity, escaped values, multiline options, defaults, required email, real native form selection, fail-closed endpoint, metadata false, server errors and four host presets (explicit Shopify transport adapters).');
})().catch(e=>{console.error(e);process.exit(1)});
