const assert=require('node:assert/strict'),f=require('./support/forms.cjs');
const names=['call-to-action-quote-form','form-quote-full','form-compact','form-support-request'];
const fonts={family:'Fixture Heading',fallback_families:'sans-serif'};
const globalSettings={color_primary:'#123456',text_base:'#654321',text_muted:'#345678',text_on_color:'#fafafa',button_radius:7,button_border_width:2,button_variant_default:'outline',font_heading:fonts,marketing_map_name:false,marketing_map_phone:false,marketing_map_company:false,marketing_double_opt_in:false,forms_captcha_provider:'turnstile',captcha_turnstile_site_key:'global-key',forms_global_endpoint:'/apps/forms'};
function inspect(html,id){const d=f.dom('<style>'+f.read('assets/forms-sections.css')+f.read('assets/call-to-action-quote-form.css')+'</style>'+html);const doc=d.window.document,host=doc.querySelector('[data-q-form-host]');assert(host,'root');assert(host.classList.contains('q-form-scope-'+id));assert(!html.includes('NaN'));assert(!html.includes('undefined'));const ids=[...doc.querySelectorAll('[id]')].map(el=>el.id);assert.equal(ids.length,new Set(ids).size,'unique ids');for(const el of host.querySelectorAll('[aria-describedby]'))for(const id of el.getAttribute('aria-describedby').split(/\s+/))assert(doc.getElementById(id),id);return d;}
(async()=>{
 let cases=0;
 for(const name of names){
  const{schema}=f.unpack(name);
  for(const preset of schema.presets){const d=inspect(await f.host(name,{id:name,settings:preset.settings,blocks:preset.blocks}),name);assert.equal(d.window.document.querySelectorAll('form').length,1);if(name!=='call-to-action-quote-form')assert.equal(d.window.document.querySelector('select').style.appearance,'auto');d.window.close();cases++;}
  for(const setting of schema.settings){
   const values=setting.type==='select'?setting.options.map(o=>o.value):setting.type==='range'?[setting.min,setting.max]:setting.type==='checkbox'?[false,true]:[];
   for(const value of values){const d=inspect(await f.host(name,{id:name,settings:{[setting.id]:value,endpoint_url:'/apps/forms'}}),name);d.window.close();cases++;}
  }
  let d=inspect(await f.host(name,{id:name,settings:{kicker:'<Kicker>',heading:'<Heading>',subheading:'<Subheading>',aria_label:'" Accessible',anchor_id:'a:日本語[quote]"',padding_x:0,padding_y:0,input_radius:0,input_border:schema.settings.find(x=>x.id==='input_border').type==='range'?0:'#123123',card_radius:0,card_shadow:schema.settings.find(x=>x.id==='card_shadow').type==='range'?0:'none',hide_on_mobile:true,hide_on_desktop:true},globals:{settings:globalSettings,request:{design_mode:true}}}),name);
  let doc=d.window.document,host=doc.querySelector('[data-q-form-host]');assert.equal(host.getAttribute('aria-label'),'" Accessible');assert(doc.getElementById('a:日本語[quote]"'));assert(!doc.querySelector('kicker,heading,subheading'));assert(!host.classList.contains('hide-mobile'));assert(!host.classList.contains('hide-desktop'));assert(host.querySelector('button.q-btn--outline'));
  const styles=[...doc.querySelectorAll('style')].map(x=>x.textContent).join(' ')+host.getAttribute('style');assert.match(styles,/--q-pad-y:\s*0(?:px|rem)/);assert.match(styles,/--q-pad-x:\s*0(?:px|rem)/);assert(styles.includes('#123456'));assert(styles.includes('#654321'));assert(!styles.includes('#a:日本語'),'anchor never becomes CSS selector');
  if(name==='form-quote-full'||name==='form-compact'){assert.equal(host.dataset.marketingMapName,'false');assert.equal(host.dataset.marketingDoubleOptIn,'false');assert(!styles.includes('direction: rtl'));assert(!styles.includes('form_surface_start'));}
  d.window.close();
  for(const side of ['left','right']){
   d=inspect(await f.host(name,{id:name,settings:{template_style:'split',split_media_side:side,split_image:f.photo()}}),name);doc=d.window.document;assert.equal(doc.querySelectorAll('.q-media-card img,aside.q-media img').length,1);assert.equal(doc.querySelector('.q-media-card img,aside.q-media img').alt,'Photo <safe>');d.window.close();
  }
  d=inspect(await f.host(name,{id:name,settings:{template_style:'split',split_image:null,kicker:'',heading:'',subheading:''}}),name);doc=d.window.document;assert(!doc.querySelector('aside,.q-media-card'));assert(!doc.querySelector('.q-split,.q-grid.split-left,.q-grid.split-right'));assert(!doc.querySelector('.q-head h2,.q-head h3,.q-head p'));d.window.close();
  d=inspect(await f.host(name,{id:name,settings:{destination:'custom_endpoint',endpoint_url:''},globals:{settings:{}}}),name);assert(!d.window.document.querySelector('form'));assert.match(d.window.document.querySelector('[role=status]').textContent,/unavailable/);d.window.close();
  d=inspect(await f.host(name,{id:name,settings:{destination:'custom_endpoint',endpoint_url:'',captcha_mode:schema.settings.find(x=>x.id==='captcha_mode').options.some(x=>x.value==='inherit')?'inherit':'turnstile'},globals:{settings:globalSettings}}),name);host=d.window.document.querySelector('[data-q-form-host]');assert.equal(host.querySelector('form').getAttribute('action'),'/apps/forms');assert.equal(host.dataset.captcha,'turnstile');assert.equal(host.dataset.captchaKey,'global-key');d.window.close();
  d=inspect(await f.host(name,{id:name,settings:{bg_video:'https://cdn.example.test/bg.mp4',bg_image:f.photo(),overlay_type:'gradient',overlay_opacity:0,grad_start_opacity:0,grad_end_opacity:0,grad_angle:0,gradient_angle:0}}),name);doc=d.window.document;assert(doc.querySelector('video'));assert(!doc.querySelector('video').autoplay);assert(doc.querySelector('img.q-form-poster'));assert(doc.querySelector('[data-video-hero-toggle]').hidden);assert.match(doc.querySelector('.q-overlay').getAttribute('style'),/0deg/);assert.match(doc.querySelector('.q-overlay').getAttribute('style'),/rgba\(0,0,0,0\)/);d.window.close();
 }
 for(const name of names){const d=inspect(await f.host(name,{id:name,globals:{settings:{text_base:'#ffffff',text_muted:'#ffffff'}}}),name);const text=[...d.window.document.querySelectorAll('style')].map(x=>x.textContent).join(' ');assert(text.includes('--q-text:#000000;'),name+' readable opaque form surface');assert(text.includes('color:#000000;box-sizing:border-box;'),name+' readable white inputs');d.window.close();}
 assert.equal(f.unpack('form-compact').schema.name,'Forms – Compact');
 let d=inspect(await f.host('form-support-request',{id:'support',settings:{destination:'custom_endpoint',endpoint_url:'/apps/forms'}}),'support');assert.equal(d.window.document.querySelector('[name=source]').value,'support-request');d.window.close();
 d=f.dom(await f.host('form-quote-full',{settings:{destination:'shopify_customer'},blocks:[f.field('email','email'),f.field('email2','email',{name_attr:'contact[email]'}),f.field('file','file',{required:true}),f.field('password','password',{required:true})]}));let doc=d.window.document;
 assert.equal(doc.querySelectorAll('[type=email][name="contact[email]"]').length,1);assert.equal(doc.querySelectorAll('[type=email]').length,2);assert(doc.querySelector('[type=url][required]'));assert(!doc.querySelector('[type=password]'));assert(doc.querySelector('[name="contact[marketing_confirmation]"][required]'));assert(!doc.querySelector('[name="contact[marketing_confirmation]"]').checked);d.window.close();
 const urls=[['http://www.youtube.com/watch?v=dQw4w9WgXcQ','youtube-nocookie.com/embed/dQw4w9WgXcQ'],['https://youtu.be/dQw4w9WgXcQ?feature=share','youtube-nocookie.com/embed/dQw4w9WgXcQ'],['https://www.youtube.com/watch?feature=share&v=dQw4w9WgXcQ','youtube-nocookie.com/embed/dQw4w9WgXcQ'],['https://www.youtube.com/shorts/dQw4w9WgXcQ','youtube-nocookie.com/embed/dQw4w9WgXcQ'],['https://vimeo.com/12345/privatehash','player.vimeo.com/video/12345'],['https://player.vimeo.com/video/12345?h=privatehash','player.vimeo.com/video/12345']];
 for(const[url,expected]of urls){d=f.dom(await f.host('call-to-action-quote-form',{settings:{bg_video:url}}));const frame=d.window.document.querySelector('iframe');assert(frame, url);assert(frame.hidden);assert(!frame.hasAttribute('src'));assert(frame.dataset.videoHeroSrc.includes(expected));if(url.includes('vimeo'))assert(frame.dataset.videoHeroSrc.includes('h=privatehash'));d.window.close();}
 for(const url of ['https://youtube.com.evil.test/watch?v=dQw4w9WgXcQ','javascript:alert(1)','https://youtu.be/invalid','https://vimeo.com/not-a-number']){d=f.dom(await f.host('call-to-action-quote-form',{settings:{bg_video:url},globals:{request:{design_mode:true}}}));assert(!d.window.document.querySelector('iframe,video'));assert(d.window.document.querySelector('.q-form-media-guide'));d.window.close();}
 const first=await f.host('call-to-action-quote-form',{id:'first',settings:{bg_video:'https://cdn.example.test/bg.mp4'}}),second=await f.host('form-support-request',{id:'second',settings:{bg_video:'https://youtu.be/dQw4w9WgXcQ'}});d=f.dom(first+second);const w=d.window;doc=w.document;const queries=new Map();
 w.matchMedia=q=>{if(!queries.has(q)){const target=new w.EventTarget();target.matches=q.includes('prefers-reduced-motion');queries.set(q,target);}return queries.get(q)};
 w.HTMLMediaElement.prototype.play=function(){this.dataset.playing='true';return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){this.dataset.playing='false'};
 f.boot(w,['frontend-form-logic.js','frontend-form-logic-form-sections.js','video-hero-banner.js']);const roots=[...doc.querySelectorAll('[data-q-form-host]')],video=doc.querySelector('video'),frame=doc.querySelector('iframe');assert.equal(video.dataset.playing,'false');assert(!frame.hasAttribute('src'));
 roots[0].querySelector('[data-video-hero-toggle]').click();assert.equal(video.dataset.playing,'true');assert(!frame.hasAttribute('src'));roots[1].querySelector('[data-video-hero-toggle]').click();assert(frame.hasAttribute('src'));
 Object.defineProperty(doc,'hidden',{configurable:true,value:true});doc.dispatchEvent(new w.Event('visibilitychange'));assert.equal(video.dataset.playing,'false');assert(!frame.hasAttribute('src'));
 roots[0].dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(roots[0].querySelector('[data-video-hero-toggle]').hidden);assert(!roots[0].querySelector('form').dataset.qValidateInit);assert(roots[1].querySelector('form').dataset.qValidateInit);w.close();
 d=f.dom(first);d.window.Shopify={designMode:true};d.window.HTMLMediaElement.prototype.pause=function(){this.dataset.playing='false'};d.window.HTMLMediaElement.prototype.play=function(){assert.fail('editor autoplay')};f.boot(d.window,['video-hero-banner.js']);assert.equal(d.window.document.querySelector('video').dataset.playing,'false');d.window.close();
 console.log('PASS four independent quote/support hosts: '+cases+' saved preset and setting endpoints; native/custom routing, marketing confirmation, file/password capabilities, scoped anchors/colors/zero/blank/media/layout controls and shared media lifecycle (explicit native/color/image/provider adapters).');
})().catch(e=>{console.error(e);process.exit(1)});
