const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');
const funnel='3rd-party-marketing-funnel-cta-strip',powered='3rd-party-powered-by',prefixes={[funnel]:'q-funnel-',[powered]:'q-powered-by-'};
const links={primary_button_label:'Explore <safe>',primary_button_url:'/fr/pages/program?a="quote"&b=2',secondary_button_label:'Read <safe>',secondary_button_url:'/fr/pages/details?x=1&y=2'};
const provider=(settings={})=>({type:'integration',settings:{name:'Alpha Beta <safe>',role:'Role <safe>',description:'<p>Native <a href="/fr/pages/info">information</a></p>',link:'/fr/pages/provider?a="quote"&b=2',...settings}});
let cases=0;
async function inspect(name,opts,fn){const html=await f.host(name,opts),d=f.dom(html);try{assert.doesNotMatch(html,/Liquid error|NaN|undefined/);for(const el of d.window.document.querySelectorAll('style'))postcss.parse(el.textContent).walkRules(rule=>{for(const selector of rule.selectors)assert(selector.startsWith('#'+prefixes[name]+(opts.id||'one')),selector)});fn(d.window.document,d.window);cases++}finally{d.window.close()}}
const css=doc=>[...doc.querySelectorAll('style')].map(el=>el.textContent).join('\n');
(async()=>{
 for(const name of [funnel,powered]){
  const schema=f.unpack(name).schema;for(const preset of schema.presets)await inspect(name,{settings:preset.settings||{},blocks:preset.blocks},doc=>{assert(doc.querySelector('section'));assert.equal(doc.querySelectorAll('.q-btn[href],.q-powered-by__cta[href]').length,0,'no invented provider/destination links')});
  for(const setting of schema.settings){const values=setting.options?.map(x=>x.value)||(setting.type==='range'?[setting.min,setting.max]:setting.type==='checkbox'?[false,true]:[]);for(const value of values)await inspect(name,{settings:{...links,[setting.id]:value},...(name===powered?{blocks:[provider({logo:f.photo()})]}:{})},doc=>assert.equal(!!doc.querySelector('section'),setting.id!=='enable_section'||value===true))}
  for(const design of [false,true]){
   await inspect(name,{settings:{enable_section:false},globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(!!doc.querySelector('[role=status]'),design)});
   await inspect(name,{settings:{kicker:'',heading:'',body:'',primary_button_label:'',secondary_button_label:'',show_funnel_tag:false},blocks:[],globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(!!doc.querySelector('[role=status]'),design)});
  }
  await inspect(name,{settings:{...links,aria_label:'',heading:'Heading <safe>'},...(name===powered?{blocks:[provider()]}:{})},doc=>{assert.equal(doc.querySelector('section').getAttribute('aria-label'),'Heading <safe>');assert.equal(doc.querySelector('h2').textContent.trim(),'Heading <safe>');assert.equal(doc.querySelector('script,form'),null);});
  const d=f.dom(await f.host(name,{id:'first',settings:{...links,align:'left',use_custom_colors:true}})+await f.host(name,{id:'second',settings:{...links,align:'center',use_custom_colors:false}}));const ids=[...d.window.document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(ids.length,new Set(ids).size);assert.equal(d.window.document.querySelectorAll('section').length,2);d.window.close();
 }
 for(const variant of ['solid','outline','ghost'])for(const custom of [false,true])await inspect(funnel,{settings:{...links,primary_button_variant:variant,secondary_button_variant:variant,enable_custom_button_colors:custom,primary_btn_bg:'#102030',primary_btn_text:'#f0f0f0',secondary_btn_bg:'#304050',secondary_btn_text:'#eeeeee',secondary_btn_border:'#8899aa',open_in_new_tab:true}},doc=>{const buttons=doc.querySelectorAll('.q-btn');assert.equal(buttons.length,2);for(const btn of buttons){assert(btn.classList.contains('q-btn--'+variant));assert.equal(btn.target,'_blank');assert.equal(btn.rel,'noopener noreferrer');assert(!btn.hasAttribute('quote'))}assert.equal(buttons[0].getAttribute('href'),links.primary_button_url);assert.equal(buttons[1].getAttribute('href'),links.secondary_button_url);assert.equal(doc.querySelector('section').hasAttribute('data-custom-btn'),custom);assert.equal(doc.querySelector('section').style.getPropertyValue('--q-cta-primary-bg').trim(),'#102030');assert(css(doc).includes('.q-cta-strip__btn.q-btn--'+variant+'{'));assert(css(doc).includes('--q-funnel-outline-text:var(--q-cta-secondary-text)'));});
 for(const variant of ['solid','outline','ghost'])await inspect(funnel,{settings:{...links,primary_button_variant:'inherit',secondary_button_variant:'inherit'},globals:{settings:{button_variant_default:variant}}},doc=>{for(const a of doc.querySelectorAll('.q-btn'))assert(a.classList.contains('q-btn--'+variant))});
 for(const layout of ['strip','card','hero'])for(const align of ['left','center'])await inspect(funnel,{settings:{...links,layout_style:layout,align,max_width:'sm',show_border:true,show_icon_hint:false}},doc=>{assert.equal(!!doc.querySelector('.q-cta-strip__card'),layout==='card');assert.equal(doc.querySelector('.q-cta-strip__icon'),null);assert(css(doc).includes('max-width:var(--container-sm,960px)'));assert(css(doc).includes('.has-actions.has-copy .q-align-left .q-cta-strip__layout'));assert(doc.querySelector('section').classList.contains('has-actions'));});
 await inspect(funnel,{settings:{primary_button_url:'',secondary_button_url:''}},doc=>{assert.equal(doc.querySelector('a.q-btn'),null);assert(!doc.querySelector('section').classList.contains('has-actions'))});
 await inspect(funnel,{settings:{kicker:'',heading:'',body:'',show_funnel_tag:true,funnel_tag_text:'Provider <safe>'}},doc=>{assert.equal(doc.querySelector('.q-cta-strip__layout'),null);assert.equal(doc.querySelector('.q-cta-strip__meta').textContent,'Provider <safe>')});
 for(const show of [false,true])await inspect(funnel,{settings:{...links,show_funnel_tag:show,funnel_tag_text:'Provider',show_icon_hint:show,open_in_new_tab:false}},doc=>{assert.equal(!!doc.querySelector('.q-cta-strip__meta'),show);assert.equal(!!doc.querySelector('.q-cta-strip__icon'),show);assert.equal(doc.querySelector('a.q-btn').target,'')});
 const colors={custom_bg_color:'#102030',custom_card_bg_color:'#203040',custom_text_color:'#ffffff',custom_muted_text_color:'#eeeeee',custom_border_color:'#8899aa',custom_accent_color:'#ffffff'};
 for(const style of ['link','button_primary','button_secondary','button_ghost'])await inspect(powered,{settings:{cta_style:style,cta_label:'Visit <safe>',use_custom_colors:true,...colors,padding_x:0,padding_y:0,card_radius:0,card_shadow_strength:0,show_border:true},blocks:[provider({logo:f.photo()})]},doc=>{const root=doc.querySelector('section'),cta=doc.querySelector('.q-powered-by__cta');assert.equal(cta.getAttribute('href'),provider().settings.link);assert.equal(cta.getAttribute('aria-label'),'Visit <safe>: Alpha Beta <safe>');assert.equal(cta.classList.contains('q-powered-by__cta--btn'),style!=='link');assert.equal(root.style.getPropertyValue('--q-powered-pad-y').trim(),'0rem');assert.equal(root.style.getPropertyValue('--q-powered-pad-x').trim(),'0rem');assert.equal(root.style.getPropertyValue('--q-powered-card-radius').trim(),'0px');assert.equal(root.style.getPropertyValue('--q-powered-accent-text').trim(),'#000000');for(const color of Object.values(colors))assert(css(doc).includes(color));assert(css(doc).includes('.q-powered-by__item:hover{box-shadow:none;}'));assert(css(doc).includes('max(0px,calc(var(--q-powered-card-radius) - 6px))'));assert(doc.querySelector('.q-powered-by__item--bordered'));const image=doc.querySelector('img');assert.equal(image.alt,'Photo <safe>');assert(image.width&&image.height);assert.equal(image.parentElement.getAttribute('aria-hidden'),'true');});
 await inspect(powered,{blocks:[provider({name:'',logo:f.photo()})],settings:{open_links_in_new_tab:false}},doc=>{assert.equal(doc.querySelector('img').parentElement.getAttribute('aria-hidden'),null);assert.equal(doc.querySelector('h3'),null);assert.equal(doc.querySelector('.q-powered-by__cta').getAttribute('aria-label'),'Learn more');assert.equal(doc.querySelector('.q-powered-by__cta').target,'')});
 await inspect(powered,{settings:{kicker:'',heading:'',body:'',cta_label:''},blocks:[provider({name:'',role:'',description:'',link:'/fr/pages/provider'})]},doc=>assert.equal(doc.querySelector('section'),null));
 await inspect(powered,{blocks:[provider({name:'',role:'',description:'',link:'',logo:''}),provider({name:'Alpha   Beta'})]},doc=>{assert.equal(doc.querySelectorAll('article').length,1);assert.equal(doc.querySelector('.q-powered-by__mark-text').textContent,'AB');assert.equal(doc.querySelectorAll('[data-editor-block]').length,1)});
 await inspect(powered,{settings:{kicker:'',heading:'',body:'',cta_label:''},blocks:[provider()]},doc=>{assert.equal(doc.querySelector('header'),null);assert.equal(doc.querySelector('.q-powered-by__cta'),null);assert.equal(doc.querySelectorAll('article').length,1)});
 for(const layout of ['grid','strip'])await inspect(powered,{settings:{layout_style:layout,card_shadow_strength:0}},(doc,w)=>assert.equal(w.getComputedStyle(doc.querySelector('.q-powered-by__item')).boxShadow,'none'));
 for(const width of ['sm','md','lg'])await inspect(powered,{settings:{max_width:width}},doc=>assert(css(doc).includes('max-width:var(--container-'+width+',')));
 for(const name of [funnel,powered])await inspect(name,{settings:links},doc=>{assert.match(css(doc),/prefers-reduced-motion/);assert.match(css(doc),/forced-colors/);assert.match(css(doc),/a:focus-visible/);assert.doesNotMatch(css(doc),/white-space:\s*nowrap/);});
 console.log('PASS '+cases+' independent Funnel CTA/Powered By preset/settings/native-link/variant/color/zero/empty/logo/initials cases, scoped CSS and separate instances. Explicit Liquid/DOM/image/color/CSS adapters do not certify Shopify/editor/pixels/AT or installed provider services.');
})().catch(e=>{console.error(e);process.exit(1)});
