const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');let cases=0;
const names=['basic-google-map','location-contact','service-area-map-banner','store-locator'];
const blocks=[{id:'a',type:'location',settings:{name:'Zero <safe>',address:'Zero Street\nTown 123',lat:'0',lng:'0',tags:'Shop, Service',phone:'(123) 456',email:'hello@example.test',url:'/pages/zero'}},{id:'b',type:'location',settings:{name:'Second',address:'Other Road',lat:'12',lng:'23',tags:'SHOP, Wholesale'}},{id:'c',type:'location',settings:{name:'Invalid coordinates',address:'Third Road',lat:'99',lng:'none',tags:'Other'}}];
async function render(name,opts={}){return f.host('maps-'+name,{blocks:name==='store-locator'?blocks:[],...opts})}
async function check(name,opts,fn){const h=await render(name,opts),d=f.dom(h);try{assert.doesNotMatch(h,/Liquid error|NaN|undefined/);fn(d.window.document,d.window,h);cases++;}finally{d.window.close()}}
function boot(w){f.boot(w,['maps-locator.js'])}
function api(w){const state={maps:[],markers:[],removed:0,cleared:0};w.google={maps:{Map:class{constructor(el,options){this.options=options;state.maps.push(this)}setCenter(v){this.center=v}setZoom(v){this.zoom=v}fitBounds(v){this.bounds=v}panTo(v){this.pan=v}unbindAll(){state.cleared++}},Marker:class{constructor(options){Object.assign(this,options);state.markers.push(this)}addListener(type,fn){this.click=fn;return{remove:()=>state.removed++}}setMap(map){this.map=map}},InfoWindow:class{setContent(x){this.content=x}open(){}close(){}},LatLngBounds:class{constructor(){this.points=[]}extend(p){this.points.push(p)}},event:{clearInstanceListeners(){state.cleared++}}}};return state;}
(async()=>{
 for(const name of names){
  await check(name,{},doc=>{assert.equal(doc.querySelector('[onerror]'),null);if(name==='service-area-map-banner')assert(doc.querySelector('.q-mapBanner__contentWrap').closest('section'));if(name!=='store-locator'){assert.equal(doc.querySelector('iframe'),null);assert(![...doc.querySelectorAll('a')].some(x=>/google\.com/.test(x.href)));}else{assert.equal(doc.querySelectorAll('[data-location-card]').length,3);assert.equal(doc.querySelectorAll('[data-location-coordinates="0,0"]').length,1);assert(doc.querySelector('[data-map-pane]').hidden);}});
  for(const st of f.unpack('maps-'+name).schema.settings)for(const value of st.options?.map(x=>x.value)||(st.type==='range'?[st.min,st.max]:st.type==='checkbox'?[false,true]:[]))await check(name,{settings:{[st.id]:value}},(doc,w,h)=>{for(const style of doc.querySelectorAll('style')){const ast=postcss.parse(style.textContent);ast.walkRules(rule=>{if(!rule.parent.name?.includes('keyframes'))for(const sel of rule.selectors)assert(sel.trim().startsWith('#'),sel);});}assert(!h.includes('| }}'));});
 }
 for(const [lat,lng,expected]of [['0','0','0,0'],['-90','180','-90,180'],['.5','-0.25','0.5,-0.25'],['','0',''],['none','0',''],['91','1',''],['0','-181',''],['1-2','3',''],['1..2','4',''],['-','3',''],['1,2','3','']]){const result=await f.engine.parseAndRender(f.read('snippets/maps-coordinates.liquid'),{lat,lng});assert.equal(result.trim(),expected);cases++;}
 await check('basic-google-map',{settings:{mode:'address',address:'A & B, München'}},doc=>{const link=doc.querySelector('a[href*="google"]');assert.equal(new URL(link.href).searchParams.get('query'),'A & B, München');assert(!link.href.startsWith('https://shop.test/https%'));});
 await check('basic-google-map',{settings:{mode:'coords',lat:'0',lng:'-45',zoom:5}},doc=>{const u=new URL(doc.querySelector('a[href*="google"]').href);assert.equal(u.searchParams.get('center'),'0,-45');assert.equal(u.searchParams.get('zoom'),'5');});
 for(const quote of ['"',"'"])for(const src of ['https://www.google.com/maps/embed?x=1','javascript:bad?https://x.test'])for(const name of ['basic-google-map','location-contact','service-area-map-banner'])await check(name,{settings:{mode:'embed',map_source:'embed_iframe',embed_code:'<iframe src='+quote+src+quote+' title="Merchant map" sandbox="allow-scripts"></iframe>'}},doc=>{assert.equal(doc.querySelectorAll('iframe').length,src.startsWith('https:')?1:0);if(name==='service-area-map-banner'&&src.startsWith('https:')){const frame=doc.querySelector('iframe');assert.equal(frame.getAttribute('sandbox'),'allow-scripts');assert(frame.closest('[inert]'));}});
 await check('location-contact',{settings:{map_source:'coords',lat:'0',lng:'0',address:'Other Place',pad_y:48,pad_x:20,gap:24,shadow_strength:0,radius:0}},(doc,w,h)=>{assert.match(doc.querySelector('iframe').src,/q=0,0/);const style=doc.querySelector('section').getAttribute('style');assert.match(style,/--qmc-pad-y: 48px/);assert.match(style,/--qmc-shadow: 0/);assert.match(style,/--qmc-radius: 0px/);});
 await check('location-contact',{settings:{heading:'<img onerror=bad()>',address:'<b>Street</b>',phone:'" onerror="x',email:'x"@example.test'}},doc=>assert.equal(doc.querySelector('[onerror],b'),null));
 await check('service-area-map-banner',{settings:{mode:'embed',embed_interactive:true,embed_code:'<iframe src="https://www.google.com/maps/embed" title="Map"></iframe>',overlay_opacity:0,radius:0}},doc=>{assert(!doc.querySelector('iframe').closest('[inert],[aria-hidden="true"]'));assert.match(doc.querySelector('section').getAttribute('style'),/--q-overlay-opacity: 0/);});
 await check('store-locator',{blocks:[]},doc=>assert.equal(doc.querySelector('section'),null));
 await check('store-locator',{blocks:[{type:'location',settings:{}}],globals:{request:{design_mode:true}}},doc=>assert.match(doc.body.textContent,/Add this location/));
 await check('store-locator',{settings:{dev_preview_map:true},globals:{request:{design_mode:false}}},doc=>assert.equal(doc.querySelector('[data-map-preview]'),null));
 // Native cards survive no JS, exact normalized tag filtering, no matches and independent editor lifecycle.
 {const d=f.dom(await render('store-locator',{id:'a'})+await render('store-locator',{id:'b'})),w=d.window,doc=w.document;boot(w);const [a,b]=doc.querySelectorAll('.q-map-locator'),visible=r=>[...r.querySelectorAll('[data-location-card]')].filter(c=>!c.hidden);assert.equal(a.querySelectorAll('[data-filter-chips] button').length,5);[...a.querySelectorAll('[data-filter-chips] button')].find(x=>x.textContent==='Shop').click();assert.equal(visible(a).length,2);assert.equal(visible(b).length,3);const input=a.querySelector('input');input.value='Other Road';input.dispatchEvent(new w.Event('input'));assert.equal(visible(a).length,1);input.value='missing';input.dispatchEvent(new w.Event('input'));assert(!a.querySelector('[data-map-empty]').hidden);a.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert.equal(visible(a).length,3);assert(a.querySelector('[data-map-controls]').hidden);a.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));assert(!a.querySelector('[data-map-controls]').hidden);assert.equal(doc.querySelectorAll('script[src*="maps.googleapis"]').length,0);cases+=8;w.close();}
 // Explicit Maps API adapter proves one loader, zero-coordinate pins, filtering, disposal and late response safety.
 {const opts={globals:{settings:{gmap_enable:true,gmap_api_key:'public-test-key',color_primary:'#111',text_on_color:'#fff'}}},d=f.dom(await render('store-locator',{...opts,id:'a'})+await render('store-locator',{...opts,id:'b'})),w=d.window,doc=w.document;boot(w);const scripts=doc.querySelectorAll('script[src*="maps.googleapis"]');assert.equal(scripts.length,1);const [a,b]=doc.querySelectorAll('.q-map-locator');a.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));const state=api(w),callback=new URL(scripts[0].src).searchParams.get('callback');w[callback]();await f.drain();assert.equal(state.maps.length,1);assert.equal(state.markers.length,2);assert.deepEqual(JSON.parse(JSON.stringify(state.markers[0].position)),{lat:0,lng:0});assert(a.querySelector('[data-map-pane]').hidden);assert(!b.querySelector('[data-map-pane]').hidden);state.markers[0].click();assert.equal(doc.activeElement.dataset.locationId,'a');const search=b.querySelector('input');search.value='Other Road';search.dispatchEvent(new w.Event('input'));assert.equal(state.markers[0].map,null);assert(state.markers[1].map);b.dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert.equal(state.removed,2);assert.equal(state.cleared,2);assert(state.markers.every(m=>!m.map));b.dispatchEvent(new w.Event('shopify:section:load',{bubbles:true}));await f.drain();assert.equal(state.maps.length,2);assert.equal(doc.querySelectorAll('script[src*="maps.googleapis"]').length,1);cases+=12;w.close();}
 {const d=f.dom(await render('store-locator',{globals:{settings:{gmap_enable:true,gmap_api_key:'public-test-key'}}})),w=d.window,doc=w.document;boot(w);doc.querySelector('script[src*="maps.googleapis"]').dispatchEvent(new w.Event('error'));await f.drain();assert(doc.querySelector('[data-map-pane]').hidden);assert.equal(doc.querySelectorAll('[data-location-card]:not([hidden])').length,3);assert.equal(doc.querySelectorAll('script[src*="maps.googleapis"]').length,0);cases+=3;w.close();}
 {const d=f.dom(await render('store-locator',{settings:{dev_preview_map:true},globals:{request:{design_mode:true}}})),w=d.window,doc=w.document;boot(w);const preview=doc.querySelector('[data-map-preview]');assert(!preview.hidden);assert.equal(preview.querySelectorAll('button').length,2);preview.querySelector('button').click();assert.equal(doc.activeElement.dataset.locationId,'a');cases+=3;w.close();}
 postcss.parse(f.read('assets/maps-locator.css'));cases++;
 console.log('PASS '+cases+' actual map settings/native cards/coordinates/URL/embed/color/zero/scoping and shared-loader/filter/provider failure/independent lifecycle/editor-preview cases. Google Maps, browser pixels and AT remain live acceptance; geometry/API calls are explicit adapters.');
})().catch(e=>{console.error(e);process.exit(1)});
