const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');
const affiliate='3rd-party-affiliate-program-cta',rewards='3rd-party-rewards-program-cta';
const prefixes={[affiliate]:'affiliate-cta-',[rewards]:'rewards-cta-'};
const sampleLinks={primary_button_label:'Join <safe>',primary_button_url:'/fr/pages/program?a="quoted"&b=2',secondary_button_label:'Terms <safe>',secondary_button_url:'/fr/pages/terms?a=1&b=2'};
const schemas=Object.fromEntries([affiliate,rewards].map(n=>[n,f.unpack(n).schema]));
let cases=0;
async function inspect(name,opts,fn){const html=await f.host(name,opts),d=f.dom(html);try{assert.doesNotMatch(html,/Liquid error|NaN|undefined/);for(const el of d.window.document.querySelectorAll('style')){const ast=postcss.parse(el.textContent);ast.walkRules(rule=>{for(const selector of rule.selectors)assert(selector.startsWith('#'+prefixes[name]+(opts.id||'one')),selector)})}fn(d.window.document,d.window);cases++;}finally{d.window.close()}}
(async()=>{
 for(const name of [affiliate,rewards]){
  const schema=schemas[name];for(const preset of schema.presets)await inspect(name,{settings:preset.settings||{},blocks:preset.blocks},doc=>assert(doc.querySelector('section')));
  for(const setting of schema.settings){const values=setting.options?.map(x=>x.value)||(setting.type==='range'?[setting.min,setting.max]:setting.type==='checkbox'?[true,false]:[]);for(const value of values)await inspect(name,{settings:{[setting.id]:value}},doc=>{assert.equal(!!doc.querySelector('section'),setting.id!=='enable_section'||value===true)})}
  await inspect(name,{settings:{...sampleLinks,aria_label:'',heading:'Heading <safe>'}},doc=>{const root=doc.querySelector('section');assert.equal(root.getAttribute('aria-label'),'Heading <safe>');assert.equal(root.querySelector('h2').textContent,'Heading <safe>');const links=root.querySelectorAll('.q-btn');assert.equal(links.length,2);assert.equal(links[0].getAttribute('href'),sampleLinks.primary_button_url);assert.equal(links[0].textContent.trim(),sampleLinks.primary_button_label);assert.equal(links[1].getAttribute('href'),sampleLinks.secondary_button_url);assert(!links[0].hasAttribute('quoted'));assert(!root.querySelector('script,form'));});
  for(const design of [false,true])await inspect(name,{settings:{enable_section:false},globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(!!doc.querySelector('[role=status]'),design)});
  const empty={kicker:'',heading:'',body:'',primary_button_label:'',secondary_button_label:'',reward_highlight:'',badge_text:'',show_badge:false};
  for(const design of [false,true])await inspect(name,{settings:empty,blocks:[],globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(!!doc.querySelector('[role=status]'),design)});
  const d=f.dom(await f.host(name,{id:'first',settings:{...sampleLinks,align:'left',buttons_full_width_mobile:false}})+await f.host(name,{id:'second',settings:{...sampleLinks,align:'center',buttons_full_width_mobile:true}}));const ids=[...d.window.document.querySelectorAll('[id]')].map(el=>el.id);assert.equal(ids.length,new Set(ids).size);assert.equal(d.window.document.querySelectorAll('section').length,2);d.window.close();
 }
 for(const show of [false,true])await inspect(affiliate,{settings:{show_bullets:show,show_badges:show}},doc=>{assert.equal(doc.querySelectorAll('.q-list__item').length,show?3:0);assert.equal(doc.querySelectorAll('.q-badge').length,show?2:0)});
 await inspect(affiliate,{settings:{kicker:'',heading:'',body:'',show_bullets:false,show_badges:false}},doc=>assert.equal(doc.querySelector('section'),null));
 for(const layout of ['full_width_hero','strip','card'])for(const background of ['surface','brand','contrast'])await inspect(affiliate,{settings:{layout_style:layout,background_style:background,...sampleLinks}},doc=>{const root=doc.querySelector('section');assert(root.classList.contains('q-section--bg-'+background));assert.equal(!!root.querySelector('.q-affiliate-cta__card'),layout==='card');const css=root.querySelector('style').textContent;assert.match(css,/--q-aff-fg: var\(--q-section-fg/);assert.match(css,/--q-aff-container-lg: var\(--container-lg/);assert.match(css,/white-space: normal/);});
 const colors={custom_bg_color:'#123456',custom_card_bg_color:'#234567',custom_text_color:'#ffffff',custom_muted_text_color:'#fedcba',custom_accent_color:'#ffffff',custom_border_color:'#778899',custom_highlight_bg_color:'#345678'};
 for(const layout of ['card','strip','hero'])for(const custom of [false,true])await inspect(rewards,{settings:{...sampleLinks,...colors,layout_style:layout,use_custom_colors:custom,padding_y:0,padding_x:0,card_radius:0,show_border:true}},doc=>{const root=doc.querySelector('section'),style=root.style;assert.equal(style.getPropertyValue('--q-ref-pad-y').trim(),'0rem');assert.equal(style.getPropertyValue('--q-ref-pad-x').trim(),'0rem');assert.equal(style.getPropertyValue('--q-ref-radius').trim(),'0px');assert.equal(style.getPropertyValue('--q-ref-bg').trim(),custom?colors.custom_bg_color:'var(--q-section-bg, var(--c-bg, #ffffff))');assert.equal(style.getPropertyValue('--q-ref-card-bg').trim(),custom?colors.custom_card_bg_color:'var(--q-section-card-bg, var(--c-bg, #ffffff))');assert.equal(style.getPropertyValue('--q-ref-accent-text').trim(),custom?'#000000':'var(--c-oncolor, #ffffff)');assert.equal(!!doc.querySelector('.is-bordered'),layout==='card');assert(root.classList.contains('has-actions'));});
 await inspect(rewards,{blocks:[{type:'benefit',settings:{title:'',body:'',icon_hint:'gift'}}],settings:{...sampleLinks,open_in_new_tab:true}},doc=>{assert.equal(doc.querySelector('.q-referral-cta__benefits'),null);for(const a of doc.querySelectorAll('.q-btn')){assert.equal(a.target,'_blank');assert.equal(a.rel,'noopener noreferrer')}});
 await inspect(rewards,{settings:{primary_button_url:'',secondary_button_url:''}},doc=>{assert(!doc.querySelector('section').classList.contains('has-actions'));assert.equal(doc.querySelector('.q-referral-cta__actions'),null);assert.match(doc.querySelector('style').textContent,/:not\(\.has-actions\).*grid-template-columns:minmax\(0,1fr\)/)});
 for(const [hint,expected]of [['gift','gift'],['SPARKLES','sparkles'],['heart','heart'],['check','check'],['star','star'],['missing <unsafe>','star'],['','star']])await inspect(rewards,{blocks:[{type:'benefit',settings:{title:'Benefit <safe>',body:'Description <safe>',icon_hint:hint}}]},doc=>{const use=doc.querySelector('use');assert.equal(use.getAttribute('href'),'/assets/icons.svg#lucide-'+expected);assert(f.read('assets/icons.svg').includes('id="lucide-'+expected+'"'));assert.equal(doc.querySelector('.q-referral-cta__benefit-title').textContent,'Benefit <safe>');assert.equal(doc.querySelectorAll('[data-editor-block]').length,1)});
 for(const [shadow,expected]of [['none','none'],['sm','0 2px'],['md','0 10px'],['lg','0 18px']])await inspect(rewards,{settings:{card_shadow:shadow}},doc=>assert(doc.querySelector('section').style.getPropertyValue('--q-ref-shadow').trim().startsWith(expected)));
 for(const width of ['sm','md','lg'])await inspect(rewards,{settings:{max_width:width}},doc=>assert(doc.querySelector('style').textContent.includes('max-width:var(--container-'+width+',')));
 const markup=await f.host(rewards,{id:'first',settings:{align:'left',buttons_full_width_mobile:false}})+await f.host(rewards,{id:'second',settings:{align:'center',buttons_full_width_mobile:true}}),d=f.dom(markup);const styles=[...d.window.document.querySelectorAll('style')].map(el=>el.textContent);assert(styles[0].includes('align-self:flex-start'));assert(!styles[1].includes('align-self:flex-start'));assert(!styles[0].includes('#rewards-cta-second'));assert(!styles[1].includes('#rewards-cta-first'));d.window.close();
 console.log('PASS '+cases+' independent Affiliate/Rewards preset/settings/color/zero/empty/native link/icon cases, all layout/surface routes, instance style isolation, theme token bindings and scoped responsive/focus/reduced-motion rules. Render/DOM/CSS adapters are not Shopify, browser pixel, AT or external program certification.');
})().catch(e=>{console.error(e);process.exit(1)});
