const assert=require('node:assert/strict'),postcss=require('postcss'),f=require('./support/forms.cjs');
const crm='3rd-party-crm-form-funnel-embed',booking='3rd-party-scheduling-booking-embed';
const raw='<div id="provider-root" style="min-width:920px"><iframe title="Booking <safe>" src="https://provider.example.test/widget?x=1&amp;y=2" height="900"></iframe></div><script data-provider>window.providerBoot={configured:true};</script>';
const bullet=(text='Bullet <safe>')=>({type:'bullet',settings:{text}}),badge=(settings={})=>({type:'trust_badge',settings:{label:'Credential <safe>',logo:f.photo(),alt:'Logo <safe>',...settings}});
let cases=0;
async function inspect(name,opts,fn){const html=await f.host(name,opts),d=f.dom(html);try{assert.doesNotMatch(html,/Liquid error|NaN|undefined/);const prefix=name===crm?'third-party-crm-embed-':'third-party-scheduling-embed-';for(const style of d.window.document.querySelectorAll('style[data-q-embed-style]'))postcss.parse(style.textContent).walkRules(rule=>{for(const selector of rule.selectors)assert(selector.startsWith('#'+prefix+(opts.id||'one')),selector)});fn(d.window.document,html);cases++}finally{d.window.close()}}
(async()=>{
 for(const name of [crm,booking]){
  const schema=f.unpack(name).schema;
  for(const preset of schema.presets)for(const design of [false,true])await inspect(name,{settings:preset.settings,blocks:preset.blocks,globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(!!doc.querySelector('[role=status]'),design)});
  for(const st of schema.settings){const values=st.options?.map(x=>x.value)||(st.type==='checkbox'?[false,true]:st.type==='range'?[st.min,st.max]:[]);for(const value of values)await inspect(name,{settings:{embed_code:raw,help_url:'/fr/pages/contact',show_help_link:true,show_trust_row:true,show_bullets:true,[st.id]:value},blocks:name===crm?[bullet(),badge()]:[]},(doc,html)=>{const root=doc.querySelector('section');assert.equal(!!root,st.id!=='enable_section'||value);if(!root)return;assert(html.includes(raw),'provider code is emitted unchanged');assert.equal(doc.querySelector('iframe').getAttribute('height'),'900');assert.equal(doc.querySelectorAll('[data-provider]').length,1);assert.equal(doc.querySelector('[role=region],[role=group]').getAttribute('tabindex'),'0');if(st.id==='max_width')assert.equal(root.style.getPropertyValue('--q-embed-width').trim(),'var(--container-'+value+','+({sm:720,md:960,lg:1152}[value])+'px)');if(st.id==='iframe_min_height')assert.equal(root.style.getPropertyValue('--q-embed-min-h').trim(),value+'px');if(st.id==='iframe_mobile_min_height')assert.equal(root.style.getPropertyValue('--q-embed-min-h-mobile').trim(),value+'px');if(st.id==='show_bullets')assert.equal(!!doc.querySelector('ul'),value);if(st.id==='show_trust_row')assert.equal(!!doc.querySelector('figure'),value);if(st.id==='show_help_link')assert.equal(!!doc.querySelector('a'),value)})}
  for(const content of ['', '   ','<!-- Paste your CRM or booking embed code here -->','<!-- Paste your calendar or booking embed code here (GoHighLevel, Calendly, etc.) -->','<!-- Replace this with your GoHighLevel or Calendly embed code. -->'])await inspect(name,{settings:{embed_code:content}},doc=>assert.equal(doc.querySelector('section'),null));
  await inspect(name,{settings:{embed_code:'<script data-custom>/* provider inserts the widget */</script>',kicker:'',heading:'',subheading:'',description:'',aria_label:''},blocks:[]},(doc,html)=>{assert(doc.querySelector('[data-custom]'));assert.equal(doc.querySelector('header'),null);assert.equal(doc.querySelector('section').getAttribute('aria-label'),'Contact and booking');assert.equal(doc.querySelector('.q-third-party-crm-embed__content'),null)});
  await inspect(name,{settings:{embed_code:raw,heading:'Heading <safe>',kicker:'Kicker <safe>',subheading:'Line <safe>\nNext',description:'Line <safe>\nNext',aria_label:''}},doc=>{assert.equal(doc.querySelector('h2').textContent,'Heading <safe>');assert.equal(doc.querySelector('section').getAttribute('aria-label'),'Heading <safe>');assert(doc.querySelector('.q-section__body br'))});
  const d=f.dom(await f.host(name,{id:'first',settings:{embed_code:'<iframe title="One" src="https://provider.example.test/one"></iframe>'}})+await f.host(name,{id:'second',settings:{embed_code:'<iframe title="Two" src="https://provider.example.test/two"></iframe>'}}));const ids=[...d.window.document.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size);assert.equal(d.window.document.querySelectorAll('section').length,2);assert.equal(d.window.document.querySelectorAll('[data-q-embed-style]').length,2);d.window.close();
  assert.equal(schema.tag,'div');assert(!schema.class.split(' ').includes('q-section'),'outer Shopify wrapper does not duplicate section surface/spacing');
 }
 for(const design of [false,true])await inspect(crm,{settings:{embed_code:raw,show_bullets:true,show_trust_row:true},blocks:[bullet(''),badge({label:'',logo:null})],globals:{request:{design_mode:design}}},doc=>{assert.equal(doc.querySelector('.q-third-party-crm-embed__content'),null);assert.equal(doc.querySelector('.q-third-party-crm-embed__layout--with-content'),null);assert.equal(doc.querySelectorAll('[data-editor-block]').length,design?2:0)});
 await inspect(crm,{settings:{embed_code:raw,show_bullets:true,show_trust_row:true},blocks:[bullet(),badge({label:'',alt:''}),badge({logo:null})]},doc=>{assert.equal(doc.querySelector('li').textContent,'Bullet <safe>');assert.equal(doc.querySelectorAll('figure').length,2);assert.equal(doc.querySelector('img').alt,'Photo <safe>');assert.equal(doc.querySelector('figcaption').textContent,'Credential <safe>');assert.equal(doc.querySelectorAll('[data-editor-block]').length,3);assert(doc.querySelector('.q-third-party-crm-embed__layout--with-content'))});
 for(const settings of [{show_help_link:false},{help_text:''},{help_url:''}])await inspect(booking,{settings:{embed_code:raw,show_help_link:true,help_text:'Help <safe>',help_url:'/fr/help?a="safe"&b=2',...settings}},doc=>assert.equal(doc.querySelector('a'),null));
 await inspect(booking,{settings:{embed_code:'',show_help_link:true,help_text:'Help <safe>',help_url:'/fr/help?a="safe"&b=2'}},doc=>{assert.equal(doc.querySelector('.q-third-party-scheduling-embed__surface'),null);assert.equal(doc.querySelector('a').getAttribute('href'),'/fr/help?a="safe"&b=2');assert.equal(doc.querySelector('a').textContent,'Help <safe>')});
 await inspect(crm,{settings:{enable_section:false,embed_code:raw,show_bullets:true},blocks:[bullet(),badge()],globals:{request:{design_mode:true}}},doc=>{assert.equal(doc.querySelector('section'),null);assert.equal(doc.querySelectorAll('[data-editor-block]').length,2);assert(doc.querySelector('[role=status]'))});
 console.log('PASS '+cases+' independent CRM/Booking embed settings, exact raw-code preservation, legacy placeholders, native iframe dimensions, empty panels/columns, labels/links, blocks, native scroll focus and separate-instance cases. Provider scripts/transport/editor lifecycle, browser layout and AT remain live acceptance.');
})().catch(e=>{console.error(e);process.exit(1)});
