const assert=require('node:assert/strict'),f=require('./support/forms.cjs');let cases=0;
f.engine.registerFilter('handleize',v=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''));
const region='3rd-party-region-availability',track='3rd-party-order-tracking';
const mf=(value,type='single_line_text_field')=>({value,type}),supplier=(codes=['US'],type='list.single_line_text_field')=>({name:mf('Supplier <safe>'),region_country_codes:mf(codes,type),regions_label:mf('North <safe>'),primary_warehouse_location:mf('Warehouse <safe>'),duty_notice:mf('Duty <safe>')}),product=s=>({title:'Product <safe>',url:'/products/test',metafields:{fulfillment:{supplier:{value:s,type:'metaobject_reference'}}}});
const data=s=>({product:product(s)}),globals=(country='US',page='product')=>({request:{design_mode:false,page_type:page},localization:{country:{iso_code:country,name:'Country <safe>'}}});
async function inspect(n,opts,fn){const html=await f.host(n,opts),d=f.dom(html);try{assert.doesNotMatch(html,/Liquid error|\[object Object\]|NaN|undefined/);fn(d.window.document,d.window,html);cases++}finally{d.window.close()}}
(async()=>{
 for(const codes of [['US'],[' us '],['CA'],['RUS'],['USX'],'US, CA','RUS, CAN']){const type=typeof codes==='string'?'single_line_text_field':'list.single_line_text_field';await inspect(region,{data:data(supplier(codes,type)),globals:globals()},doc=>{const txt=doc.querySelector('.q-ra-primary').textContent;const match=Array.isArray(codes)?['US',' us '].some(v=>codes.includes(v)):codes==='US, CA';assert.equal(!!doc.querySelector('.q-ra-tone--ok'),match);assert(txt);assert.equal(doc.querySelector('section').getAttribute('aria-labelledby'),null)})}
 for(const mode of ['auto','always_generic'])for(const country of ['US','CA',''])for(const duty of ['never','when_unsupported','always'])await inspect(region,{data:data(supplier()),globals:globals(country),settings:{region_message_mode:mode,duty_notice_mode:duty}},doc=>{assert.equal(!!doc.querySelector('.q-ra-duty'),duty==='always'||(duty==='when_unsupported'&&country==='CA'&&mode==='auto'));assert.equal(!!doc.querySelector('.q-ra-tone--ok'),mode==='auto'&&country==='US')});
 for(const value of [false,true])await inspect(region,{data:data(null),globals:globals(),settings:{show_generic_when_no_supplier_data:value}},doc=>assert.equal(!!doc.querySelector('section'),value));
 for(const design of [false,true])await inspect(region,{globals:{request:{design_mode:design,page_type:'page'}},settings:{show_placeholder_outside_context:true}},doc=>assert.equal(!!doc.querySelector('.q-ra-card'),design));
 for(const mode of ['auto','always_generic'])await inspect(region,{data:{cart:{item_count:2,items:[{product:product(supplier()),url:'/products/test?variant=1'},{product:product(null)}]}},globals:globals('US','cart'),settings:{show_on_cart:true,cart_show_region_hints:true,cart_message_mode:mode}},doc=>{assert.equal(doc.querySelectorAll('.q-ra-cart__row').length,mode==='auto'?1:2);assert.equal(doc.querySelector('a').getAttribute('href'),'/products/test?variant=1');assert.match(doc.querySelector('.q-ra-cart__meta').textContent,/Supplier <safe>/)});
 await inspect(region,{data:{cart:{item_count:1,items:[{product:product(null)}]}},globals:globals('US','cart'),settings:{show_on_cart:true,cart_show_region_hints:true}},doc=>assert.equal(doc.querySelector('section'),null));
 await inspect(region,{data:data(supplier(['CA'])),globals:globals(),settings:{icon_source:'theme'}},doc=>assert.match(doc.querySelector('use').getAttribute('href'),/#lucide-triangle-alert$/));
 for(const st of f.unpack(region).schema.settings){for(const v of st.options?.map(x=>x.value)||(st.type==='range'?[st.min,st.max]:st.type==='checkbox'?[false,true]:[]))await inspect(region,{data:data(supplier()),globals:globals(),settings:{[st.id]:v}},(doc,w,html)=>{if(st.id==='enable_section'&&!v){assert.equal(doc.querySelector('section'),null);return;}if(st.id==='card_radius')assert.match(html,new RegExp('--q-ra-radius: '+v+'px'));if(st.id==='show_icon')assert.equal(!!doc.querySelector('.q-ra-icon'),v);if(st.id==='show_secondary_line')assert.equal(!!doc.querySelector('.q-ra-secondary'),v)})}
 for(const st of f.unpack(track).schema.settings){for(const v of st.options?.map(x=>x.value)||(st.type==='checkbox'?[false,true]:[]))await inspect(track,{settings:{shopify_help_url:'/pages/help',external_pattern_url:'https://provider.test/{tracking}',[st.id]:v}},doc=>{if(st.id==='enable_section'&&!v){assert.equal(doc.querySelector('form'),null);return;}assert(doc.querySelector('form').hidden);assert.equal(doc.querySelector('script').defer,true);assert.equal(doc.querySelector('script:not([src])'),null);if(st.id==='show_email_field')assert.equal(!!doc.querySelector('[name="email"]'),v)})}
 function runtime(html){const d=f.dom(html),w=d.window,doc=w.document,opened=[];w.open=(...args)=>opened.push(args);w.eval(f.read('assets/3rd-party-order-tracking.js'));doc.dispatchEvent(new w.Event('DOMContentLoaded'));return {d,w,doc,opened,submit(form){form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}))},event(el,type){el.dispatchEvent(new w.Event(type,{bubbles:true}))}}}
 const configurations=[
  {mode:'shopify_help',shopify_help_url:'/pages/help?keep=yes#status',shopify_help_append_query:true,shopify_help_query_param:'order'},
  {mode:'external_pattern',external_pattern_url:'https://provider.test/ship/{tracking}?email={email}&keep=yes#status'},
  {mode:'external_pattern',external_pattern_url:'https://provider.test/ship?keep=yes#status'},
  {mode:'external_pattern',external_pattern_url:'javascript:alert(1)',external_fallback_url:'/pages/help'}
 ];
 for(const settings of configurations){const rt=runtime(await f.host(track,{settings:{...settings,show_email_field:true,open_in_new_tab:true}}));try{const form=rt.doc.querySelector('form');assert(!form.hidden);form.elements.tracking.value='A/B &?#';form.elements.email.value='user+tag@example.test';rt.submit(form);assert.equal(rt.opened.length,1);const url=new URL(rt.opened[0][0]);assert(['https:'].includes(url.protocol));if(settings.external_fallback_url)assert.equal(url.pathname,'/pages/help');else{assert.equal(url.searchParams.get('keep'),'yes');assert.equal(url.hash,'#status');if(settings.mode==='shopify_help')assert.equal(url.searchParams.get('order'),'A/B &?#');else if(settings.external_pattern_url.includes('{tracking}'))assert.equal(decodeURIComponent(url.pathname.split('/').at(-1)),'A/B &?#');else assert.equal(url.searchParams.get('tracking'),'A/B &?#');assert.equal(url.searchParams.get('email'),'user+tag@example.test')}assert.deepEqual(rt.opened[0].slice(1),['_blank','noopener,noreferrer']);cases++}finally{rt.d.window.close()}}
 for(const endpoint of ['','javascript:alert(1)','//other.test/path','http://other.test/path','/\\other.test/path']){const rt=runtime(await f.host(track,{settings:{mode:'external_pattern',external_pattern_url:endpoint}}));try{assert(rt.doc.querySelector('form').hidden);assert.equal(rt.opened.length,0);cases++}finally{rt.d.window.close()}}
 const rt=runtime(await f.host(track,{id:'one',settings:{shopify_help_url:'/one',show_email_field:true,open_in_new_tab:true}})+await f.host(track,{id:'two',settings:{shopify_help_url:'/two',open_in_new_tab:true}}));try{const [a,b]=rt.doc.querySelectorAll('form');assert.equal(new Set([...rt.doc.querySelectorAll('[id]')].map(e=>e.id)).size,rt.doc.querySelectorAll('[id]').length);a.elements.tracking.value=' ';rt.submit(a);assert.equal(rt.opened.length,0);assert.equal(rt.doc.activeElement,a.elements.tracking);a.elements.tracking.value='123';a.elements.email.value='wrong';rt.submit(a);assert.equal(rt.opened.length,0);assert.equal(rt.doc.activeElement,a.elements.email);a.elements.email.value='';rt.w.eval(f.read('assets/3rd-party-order-tracking.js'));rt.submit(a);assert.equal(rt.opened.length,1);const root=rt.doc.getElementById('order-tracking-cta-one');rt.event(root,'shopify:section:unload');assert(a.hidden);assert(!b.hidden);rt.event(root,'shopify:section:load');assert(!a.hidden);rt.submit(a);assert.equal(rt.opened.length,2);cases+=7}finally{rt.d.window.close()}
 console.log('PASS '+cases+' tracking/region independent configuration, URL encoding/query/hash/fallback, provider boundary, two-instance lifecycle, exact typed country membership, product/cart/empty/default, icon and responsive setting cases. Native redirect, Shopify Markets/metafields, pixels and AT remain live queued.');
})().catch(e=>{console.error(e);process.exit(1)});
