const fs=require('node:fs'),assert=require('node:assert/strict');
const {Liquid}=require('liquidjs'),{JSDOM}=require('jsdom');
const source=fs.readFileSync('sections/transparent-hero-banner.liquid','utf8'),start=source.lastIndexOf('{% schema %}');
const schema=JSON.parse(source.slice(start+12).split('{% endschema %}')[0]);
const defaults=fields=>Object.fromEntries(fields.filter(x=>x.id).map(x=>[x.id,x.default??null]));
const globals=Object.assign({},...JSON.parse(fs.readFileSync('config/settings_schema.json')).map(x=>defaults(x.settings || [])));
const engine=new Liquid();engine.registerFilter('color_modify',()=> 'rgba(0,0,0,0)');
const block=id=>({id,type:schema.blocks[0].type,settings:{...defaults(schema.blocks[0].settings),video_url:`/${id}.mp4`,heading:id,cta_text:'Browse',cta_link:'/collections/all'}});
const render=(id,overrides={},blocks=[block('first'),block('second')])=>engine.parseAndRender(source.slice(0,start),{section:{id,settings:{...defaults(schema.settings),mode:'slideshow',autoplay:true,nav_arrows:true,nav_dots:true,enable_header_overlap:true,...overrides},blocks},settings:{...globals,video_autoplay:true}});
(async()=>{
 const html='<header data-header data-theme="original"></header>'+await render('one',{anchor_id:'custom:anchor',header_theme:'dark'})+await render('two',{header_theme:'light'});
 const dom=new JSDOM(html,{runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,roots=[...w.document.querySelectorAll('[data-transparent-hero]')];
 const timers=new Map();let tick=0;w.setTimeout=fn=>{timers.set(++tick,fn);return tick};w.clearTimeout=id=>timers.delete(id);
 const motion=new w.EventTarget();motion.matches=false;const mobile=new w.EventTarget();mobile.matches=false;w.matchMedia=q=>q.includes('reduced-motion')?motion:mobile;
 const observers=[];w.IntersectionObserver=class{constructor(fn){this.fn=fn;observers.push(this)}observe(root){this.root=root}disconnect(){this.disconnected=true}};
 w.HTMLMediaElement.prototype.play=function(){this.dataset.playing='true';return Promise.resolve()};w.HTMLMediaElement.prototype.pause=function(){this.dataset.playing='false'};
 roots.forEach(root=>{const track=root.querySelector('.thb-track');track.scrollTo=({left})=>{track.scrollLeft=left};root.querySelectorAll('.thb-slide').forEach((slide,i)=>Object.defineProperty(slide,'offsetLeft',{value:i*100}));});
 const script=fs.readFileSync('assets/transparent-hero-banner.js','utf8');w.eval(script);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));w.eval(script);
 assert.equal(timers.size,2);assert.equal(observers.length,2);assert.equal(roots[0].id,'custom:anchor');assert.equal(roots[0].querySelectorAll('.thb-dot[aria-label]').length,2);
 const slide0=roots[0].querySelectorAll('.thb-slide');assert.equal(slide0[0].querySelector('video').dataset.playing,'true');assert.equal(slide0[1].querySelector('video').dataset.playing,'false');assert.equal(slide0[1].inert,true);
 roots[0].querySelector('.thb-arrow--next').click();assert.equal(slide0[0].inert,true);assert.equal(slide0[0].querySelector('video').dataset.playing,'false');assert.equal(slide0[1].querySelector('video').dataset.playing,'true');
 roots[0].querySelector('[data-transparent-pause]').click();assert.equal(timers.size,1);roots[0].dispatchEvent(new w.Event('mouseleave'));assert.equal(timers.size,1,'manual pause survives mouseleave');
 const header=w.document.querySelector('header');observers.forEach(o=>o.fn([{isIntersecting:true,intersectionRatio:.8}]));assert(header.classList.contains('is-over-hero'));
 roots[0].dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert(observers[0].disconnected);assert.equal(header.dataset.theme,'light');assert.equal(timers.size,1);
 motion.matches=true;motion.dispatchEvent(new w.Event('change'));assert.equal(timers.size,0);assert.equal(roots[1].querySelector('video').dataset.playing,'false');
 roots[1].dispatchEvent(new w.CustomEvent('shopify:block:select',{bubbles:true,detail:{blockId:'second'}}));assert.equal(roots[1].querySelectorAll('.thb-slide')[1].inert,false);
 roots[1].dispatchEvent(new w.Event('shopify:section:unload',{bubbles:true}));assert.equal(header.dataset.theme,'original');assert(!header.classList.contains('is-over-hero'));assert.equal(timers.size,0);
 for(const sheet of w.document.styleSheets)for(const rule of [...sheet.cssRules].flatMap(r=>r.cssRules?[...r.cssRules]:[r]))if(rule.selectorText)for(const selector of rule.selectorText.split(','))assert(selector.trim().startsWith('#shopify-section-'),'scoped styles');
 w.close();
 const staticDom=new JSDOM(await render('static',{mode:'static'}));assert.equal(staticDom.window.document.querySelectorAll('.thb-slide').length,1);assert(!staticDom.window.document.querySelector('.thb-dot'));staticDom.window.close();
 assert(!(await render('empty',{},[])).includes('data-transparent-hero\n'),'empty storefront omits hero');
 console.log('PASS Transparent Hero: actual static/slideshow Liquid, two instances, timers and duplicate boot, slide/inert/video switching, persistent pause, editor selection/unload, reduced motion, shared header restoration and scoped CSS.');
})().catch(error=>{console.error(error);process.exitCode=1});
